package com.vcampus.server.dao;
import java.sql.*;import java.util.*;import com.vcampus.common.entity.StudentAid;import com.vcampus.common.enums.StudentAidStatus;import com.vcampus.server.util.DBUtil;
public class StudentAidDAO {
 public List<StudentAid> findByStudentId(String id)throws SQLException{List<StudentAid>o=new ArrayList<>();try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM tblStudentAid WHERE studentId=? ORDER BY aidDate DESC")){p.setString(1,id);try(ResultSet r=p.executeQuery()){while(r.next())o.add(map(r));}}return o;}
 public boolean insert(StudentAid a)throws SQLException{try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO tblStudentAid(studentId,aidName,aidType,amount,aidDate,provider,status,description) VALUES(?,?,?,?,?,?,?,?)")){bind(p,a,false);return p.executeUpdate()==1;}}
 public boolean update(StudentAid a)throws SQLException{try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("UPDATE tblStudentAid SET studentId=?,aidName=?,aidType=?,amount=?,aidDate=?,provider=?,status=?,description=? WHERE aidId=?")){bind(p,a,true);return p.executeUpdate()==1;}}
 public boolean delete(long id)throws SQLException{try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM tblStudentAid WHERE aidId=?")){p.setLong(1,id);return p.executeUpdate()==1;}}
 private static void bind(PreparedStatement p,StudentAid a,boolean id)throws SQLException{p.setString(1,a.getStudentId());p.setString(2,a.getAidName());p.setString(3,a.getAidType());p.setBigDecimal(4,a.getAmount());p.setDate(5,a.getAidDate());p.setString(6,a.getProvider());p.setString(7,a.getStatus().name());p.setString(8,a.getDescription());if(id)p.setLong(9,a.getAidId());}
 private static StudentAid map(ResultSet r)throws SQLException{StudentAid a=new StudentAid();a.setAidId(r.getLong("aidId"));a.setStudentId(r.getString("studentId"));a.setAidName(r.getString("aidName"));a.setAidType(r.getString("aidType"));a.setAmount(r.getBigDecimal("amount"));a.setAidDate(r.getDate("aidDate"));a.setProvider(r.getString("provider"));a.setStatus(StudentAidStatus.valueOf(r.getString("status")));a.setDescription(r.getString("description"));return a;}
}
