package com.vcampus.client.service;
import java.util.function.Consumer;import com.vcampus.client.network.SocketClient;import com.vcampus.common.entity.*;import com.vcampus.common.protocol.*;import com.vcampus.common.vo.StudentReviewVO;
/** 学籍客户端门面。界面控制器只需传业务对象和响应回调。 */
public class StudentClientService implements IStudentClientService {
 private final SocketClient socket; public StudentClientService(SocketClient socket){this.socket=socket;}
 private void send(MessageType type,String action,String key,Object value,Consumer<Message> callback){Message m=new Message(type,"student",action);if(key!=null)m.putData(key,value);socket.getDispatcher().onResponse(action,callback);socket.send(m);}
 public void queryOverview(Consumer<Message> c){send(MessageType.STUDENT_OVERVIEW_QUERY,"queryOverview",null,null,c);} public void submitChangeRequest(StudentChangeRequest r,Consumer<Message> c){send(MessageType.STUDENT_CHANGE_SUBMIT,"submitChangeRequest","request",r,c);} public void queryMyRequests(Consumer<Message> c){send(MessageType.STUDENT_CHANGE_LIST,"queryMyRequests",null,null,c);}
 public void cancelChangeRequest(long id,Consumer<Message> c){send(MessageType.STUDENT_CHANGE_CANCEL,"cancelChangeRequest","requestId",id,c);}
 public void listStudents(Consumer<Message> c){send(MessageType.STUDENT_LIST,"listStudents",null,null,c);} public void queryStudentOverview(String id,Consumer<Message> c){send(MessageType.STUDENT_QUERY,"queryStudentOverview","studentId",id,c);} public void listPendingRequests(Consumer<Message> c){send(MessageType.STUDENT_REVIEW_LIST,"listPendingRequests",null,null,c);} public void queryChangeRequest(long id,Consumer<Message> c){send(MessageType.STUDENT_REVIEW_QUERY,"queryChangeRequest","requestId",id,c);} public void reviewChangeRequest(StudentReviewVO r,Consumer<Message> c){send(MessageType.STUDENT_REVIEW,"reviewChangeRequest","review",r,c);}
 public void updateStudentByAdmin(Student s,Consumer<Message> c){send(MessageType.STUDENT_ADMIN_UPDATE,"updateStudentByAdmin","student",s,c);} public void addAward(StudentAward a,Consumer<Message> c){send(MessageType.STUDENT_AWARD_ADD,"addAward","award",a,c);} public void updateAward(StudentAward a,Consumer<Message> c){send(MessageType.STUDENT_AWARD_UPDATE,"updateAward","award",a,c);} public void deleteAward(long id,Consumer<Message> c){send(MessageType.STUDENT_AWARD_DELETE,"deleteAward","awardId",id,c);} public void addAid(StudentAid a,Consumer<Message> c){send(MessageType.STUDENT_AID_ADD,"addAid","aid",a,c);} public void updateAid(StudentAid a,Consumer<Message> c){send(MessageType.STUDENT_AID_UPDATE,"updateAid","aid",a,c);} public void deleteAid(long id,Consumer<Message> c){send(MessageType.STUDENT_AID_DELETE,"deleteAid","aidId",id,c);}
}
