package controller;
import app.ClientMain; import com.google.gson.*; import com.google.gson.reflect.TypeToken; import entity.*; import enums.StudentChangeStatus; import javafx.application.Platform; import javafx.beans.property.SimpleStringProperty; import javafx.collections.FXCollections; import javafx.fxml.FXML; import javafx.geometry.Pos; import javafx.scene.control.*; import javafx.scene.layout.*; import service.StudentClientService; import session.ClientSession; import protocol.*; import vo.*;
import java.lang.reflect.*; import java.sql.Date; import java.util.*;
public class StudentController {
 @FXML private Label titleLabel,statusBarLabel,avatarLabel,sidebarAvatarLabel,sidebarNameLabel,sidebarMajorLabel,nameLabel,studentMetaLabel,pendingHintLabel,categoryValue,statusValue,gradeValue,inSchoolValue;
 @FXML private TabPane studentTabs; @FXML private Tab overviewTab,detailTab,adminListTab,reviewTab; @FXML private ScrollPane detailScrollPane;
 @FXML private GridPane baseInfoGrid,studyInfoGrid,admissionInfoGrid,contactInfoGrid; @FXML private VBox studentDetailSidebar,adminDetailSidebar,reviewOverviewPane,reviewDetailPane; @FXML private Button adminReturnButton; @FXML private TextArea reviewRemarkArea; @FXML private TextField searchIdField,searchNameField,searchCollegeField,pageNumberField; @FXML private Label pageSummaryLabel;
 @FXML private TilePane awardTile,aidTile;
 @FXML private TableView<StudentChangeRequest> reviewTable; @FXML private TableColumn<StudentChangeRequest,String> reviewIdCol,reviewStudentCol,reviewTimeCol,reviewStatusCol; @FXML private TableColumn<StudentChangeRequest,Void> reviewActionCol;
 @FXML private TableView<Student> studentTable; @FXML private TableColumn<Student,String> stuIdCol,stuNameCol,stuGenderCol,stuGradeCol,stuCollegeCol,stuMajorCol,stuStatusCol; @FXML private TableColumn<Student,Void> stuActionCol;
 @FXML private TableView<StudentChangeItem> reviewItemTable; @FXML private TableColumn<StudentChangeItem,String> itemFieldCol,itemOldCol,itemNewCol; @FXML private Button approveButton,rejectButton;
 private static final int PAGE_SIZE=12; private final StudentClientService service=new StudentClientService(network.SocketClient.getInstance()); private final Gson gson=new Gson(); private final List<TextField> editable=new ArrayList<>(); private boolean editing; private StudentOverviewVO overview; private List<Student> students=new ArrayList<>(),filteredStudents=new ArrayList<>(); private int currentPage=1; private StudentChangeRequest selected;
 @FXML public void initialize(){setupTables();setupRole();refreshData();}
 private void refreshData(){setStatus("正在加载学籍信息...");if(isAdmin())loadAdmin();else service.queryOverview(this::onOverview);}
 @FXML private void handleBack(){ClientMain.switchScene("/resources/fxml/MainView.fxml");} @FXML private void handleRefresh(){refreshData();} @FXML private void handleViewDetails(){studentTabs.getSelectionModel().select(detailTab);} @FXML private void handleShowOverview(){studentTabs.getSelectionModel().select(overviewTab);} @FXML private void handleShowReview(){if(isAdmin())studentTabs.getSelectionModel().select(reviewTab);}
 @FXML private void handleEditBase(){beginGlobalEdit();} @FXML private void handleEditStudy(){beginGlobalEdit();} @FXML private void handleEditAdmission(){beginGlobalEdit();} @FXML private void handleEditContact(){beginGlobalEdit();}
 private List<String> baseFields(){return List.of("userId","studentId","name","politicalStatus","nationality","gender","idType","idNumber","idIssueDate","birthDate","nativePlace","householdType","birthPlace","sourcePlace","registeredResidence","leagueMember","leagueJoinDate","partyMember","partyJoinDate","healthStatus");} private List<String> studyFields(){return List.of("studentCategory","registered","inSchool","studentStatus","campus","grade","college","major","className","educationLevel","trainingMode","schoolingLength","counselorName","counselorPhone");} private List<String> admissionFields(){return List.of("candidateCategory","admissionDate","admissionMethod","graduationSchool","middleSchoolClass","middleSchoolTeacher");} private List<String> contactFields(){return List.of("telephone","mobile","email","qq","wechat","campusAddress","emergencyContact","emergencyPhone");}
 private void beginGlobalEdit(){if(overview==null||overview.getStudent()==null)return;if(!isAdmin()&&overview.getPendingRequest()!=null){setStatus("当前修改申请正在审核中，审核完成后才能再次修改");return;}editable.clear();editing=true;fillEditable(baseInfoGrid,baseFields());fillEditable(studyInfoGrid,studyFields());fillEditable(admissionInfoGrid,admissionFields());fillEditable(contactInfoGrid,contactFields());Button cancel=new Button("取消");cancel.getStyleClass().add("btn-secondary");cancel.setOnAction(e->cancelGlobalEdit());Button submit=new Button(isAdmin()?"提交":"提交修改申请");submit.getStyleClass().add("btn-primary");submit.setOnAction(e->handleSubmitChange());HBox actions=new HBox(8,cancel,submit);actions.setAlignment(Pos.CENTER_RIGHT);contactInfoGrid.add(actions,0,4,6,1);setStatus(isAdmin()?"全部信息已进入编辑状态，提交后直接生效":"全部信息已进入编辑状态，提交后等待审核");}
 private void fillEditable(GridPane grid,List<String> names){prepareSixColumns(grid);grid.getChildren().clear();Student s=overview.getStudent();for(int i=0;i<names.size();i++){String n=names.get(i);int[] p=fieldPosition(grid,n,i);Label key=new Label(title(n));styleFieldKey(key);TextField value=new TextField(safe(read(s,n)));value.setAlignment(Pos.CENTER_LEFT);value.setMinWidth(0);value.setMaxWidth(Double.MAX_VALUE);value.setUserData(n);value.getStyleClass().add("form-control");Tooltip.install(value,new Tooltip(value.getText()));boolean identity="userId".equals(n)||"studentId".equals(n);value.setEditable(!identity);value.setDisable(identity);if(!identity)editable.add(value);grid.add(key,p[1]*2,p[0]);grid.add(value,p[1]*2+1,p[0]);if(fieldSpansRemainder(grid,n))GridPane.setColumnSpan(value,5-p[1]*2);}} private void cancelGlobalEdit(){editing=false;render(overview);setStatus("已取消编辑");}
 @FXML private void handleIndexBase(){scrollDetail(0.0);} @FXML private void handleIndexStudy(){scrollDetail(0.34);} @FXML private void handleIndexAdmission(){scrollDetail(0.68);} @FXML private void handleIndexContact(){scrollDetail(1.0);} private void scrollDetail(double value){studentTabs.getSelectionModel().select(detailTab);Platform.runLater(()->detailScrollPane.setVvalue(value));}
 private void setupRole(){if(isAdmin()){studentTabs.getTabs().removeAll(overviewTab);titleLabel.setText("学籍管理");studentDetailSidebar.setVisible(false);studentDetailSidebar.setManaged(false);adminDetailSidebar.setVisible(true);adminDetailSidebar.setManaged(true);adminReturnButton.setVisible(true);adminReturnButton.setManaged(true);studentTabs.getSelectionModel().select(adminListTab);}else{studentTabs.getTabs().removeAll(adminListTab,reviewTab);titleLabel.setText("我的学籍");adminDetailSidebar.setVisible(false);adminDetailSidebar.setManaged(false);adminReturnButton.setVisible(false);adminReturnButton.setManaged(false);}}
 private boolean isAdmin(){String r=ClientSession.getInstance().getRole();return "ADMIN".equalsIgnoreCase(safe(r))||"管理员".equals(r);}
 private void setupTables(){
  stuIdCol.setCellValueFactory(c->text(c.getValue().getStudentId()));stuNameCol.setCellValueFactory(c->text(c.getValue().getName()));stuGenderCol.setCellValueFactory(c->text(c.getValue().getGender()));stuGradeCol.setCellValueFactory(c->text(c.getValue().getGrade()));stuCollegeCol.setCellValueFactory(c->text(c.getValue().getCollege()));stuMajorCol.setCellValueFactory(c->text(c.getValue().getMajor()));stuStatusCol.setCellValueFactory(c->text(c.getValue().getStudentStatus()));
  stuActionCol.setCellFactory(column->new TableCell<>(){private final Button button=new Button("查看详情");{button.getStyleClass().add("table-action-button");button.setOnAction(e->{Student row=getTableView().getItems().get(getIndex());showStudentDetails(row);});}protected void updateItem(Void item,boolean empty){super.updateItem(item,empty);setGraphic(empty?null:button);}});
  reviewActionCol.setCellFactory(column->new TableCell<>(){private final Button button=new Button("查看详情");{button.getStyleClass().add("table-action-button");button.setOnAction(e->{StudentChangeRequest row=getTableView().getItems().get(getIndex());showReviewDetail(row);});}protected void updateItem(Void item,boolean empty){super.updateItem(item,empty);setGraphic(empty?null:button);}});
  reviewIdCol.setCellValueFactory(c->text(c.getValue().getRequestId()));reviewStudentCol.setCellValueFactory(c->text(c.getValue().getStudentId()));reviewTimeCol.setCellValueFactory(c->text(c.getValue().getSubmitTime()));reviewStatusCol.setCellValueFactory(c->text(status(c.getValue().getStatus())));itemFieldCol.setCellValueFactory(c->text(title(c.getValue().getFieldName())));itemOldCol.setCellValueFactory(c->text(c.getValue().getOldValue()));itemNewCol.setCellValueFactory(c->text(c.getValue().getNewValue()));
  studentTable.setOnMouseClicked(e->{if(e.getClickCount()==2)handleShowSelectedStudent();});
 }
 private <T>T data(Message m,String key,Type type){Object v=m==null?null:m.getData().get(key);return v==null?null:gson.fromJson(gson.toJson(v),type);}
 private void onOverview(Message m){Platform.runLater(()->{if(!ok(m)){setStatus(message(m,"学籍信息加载失败"));return;}overview=data(m,"overview",StudentOverviewVO.class);render(overview);setStatus("学籍信息已更新");});}
 private void loadAdmin(){service.listStudents(m->Platform.runLater(()->{if(ok(m)){List<Student> v=data(m,"students",new TypeToken<List<Student>>(){}.getType());students=v==null?new ArrayList<>():v;filteredStudents=new ArrayList<>(students);currentPage=1;refreshStudentPage();}else setStatus(message(m,"学生列表加载失败"));}));service.listPendingRequests(m->Platform.runLater(()->{List<StudentChangeRequest> v=ok(m)?data(m,"requests",new TypeToken<List<StudentChangeRequest>>(){}.getType()):List.of();reviewTable.setItems(FXCollections.observableArrayList(v==null?List.of():v));}));}
 @FXML private void handleSearchStudents(){String id=safe(searchIdField.getText()).toLowerCase(),name=safe(searchNameField.getText()).toLowerCase(),college=safe(searchCollegeField.getText()).toLowerCase();filteredStudents=students.stream().filter(s->safe(s.getStudentId()).toLowerCase().contains(id)).filter(s->safe(s.getName()).toLowerCase().contains(name)).filter(s->(safe(s.getCollege())+" "+safe(s.getMajor())).toLowerCase().contains(college)).toList();currentPage=1;refreshStudentPage();}
 @FXML private void handleResetSearch(){searchIdField.clear();searchNameField.clear();searchCollegeField.clear();filteredStudents=new ArrayList<>(students);currentPage=1;refreshStudentPage();}
 @FXML private void handleShowSelectedStudent(){Student s=studentTable.getSelectionModel().getSelectedItem();if(s==null){setStatus("请先选择学生");return;}showStudentDetails(s);} private void showStudentDetails(Student s){service.queryStudentOverview(s.getStudentId(),m->{onOverview(m);Platform.runLater(()->studentTabs.getSelectionModel().select(detailTab));});} @FXML private void handleReturnToStudentList(){editing=false;studentTabs.getSelectionModel().select(adminListTab);}
 private int pageCount(){return Math.max(1,(filteredStudents.size()+PAGE_SIZE-1)/PAGE_SIZE);} private void refreshStudentPage(){currentPage=Math.max(1,Math.min(currentPage,pageCount()));int from=Math.min((currentPage-1)*PAGE_SIZE,filteredStudents.size()),to=Math.min(from+PAGE_SIZE,filteredStudents.size());studentTable.setItems(FXCollections.observableArrayList(filteredStudents.subList(from,to)));pageNumberField.setText(String.valueOf(currentPage));pageSummaryLabel.setText("共"+filteredStudents.size()+"条  共"+pageCount()+"页");}
 @FXML private void handleFirstPage(){currentPage=1;refreshStudentPage();}@FXML private void handlePreviousPage(){if(currentPage>1)currentPage--;refreshStudentPage();}@FXML private void handleNextPage(){if(currentPage<pageCount())currentPage++;refreshStudentPage();}@FXML private void handleLastPage(){currentPage=pageCount();refreshStudentPage();}@FXML private void handleGoPage(){try{currentPage=Integer.parseInt(pageNumberField.getText().trim());}catch(Exception e){setStatus("请输入有效页码");}refreshStudentPage();}
 private void handleSubmitChange(){if(overview==null||overview.getStudent()==null)return;List<StudentChangeItem> items=changedItems();if(items.isEmpty()){setStatus("没有检测到修改内容");return;}if(isAdmin()){Student updated=gson.fromJson(gson.toJson(overview.getStudent()),Student.class);try{for(TextField f:editable)write(updated,(String)f.getUserData(),f.getText());}catch(Exception e){setStatus("输入格式错误："+e.getMessage());return;}service.updateStudentByAdmin(updated,m->Platform.runLater(()->{setStatus(message(m,"学籍信息已直接更新"));if(ok(m)){editing=false;service.queryStudentOverview(updated.getStudentId(),this::onOverview);}}));return;}StudentChangeRequest r=new StudentChangeRequest();r.setItems(items);service.submitChangeRequest(r,m->Platform.runLater(()->{setStatus(message(m,"申请已提交"));if(ok(m)){editing=false;refreshData();}}));}
 private List<StudentChangeItem> changedItems(){List<StudentChangeItem> items=new ArrayList<>();for(TextField f:editable){String n=(String)f.getUserData(),old=safe(read(overview.getStudent(),n)),now=safe(f.getText());if(!old.equals(now)){StudentChangeItem i=new StudentChangeItem();i.setFieldName(n);i.setOldValue(old);i.setNewValue(now);items.add(i);}}return items;}
 private void write(Student s,String n,String value)throws Exception{String x=Character.toUpperCase(n.charAt(0))+n.substring(1);Method setter=Arrays.stream(Student.class.getMethods()).filter(m->m.getName().equals("set"+x)&&m.getParameterCount()==1).findFirst().orElseThrow();Class<?> type=setter.getParameterTypes()[0];Object converted;if(type==String.class)converted=value.trim();else if(type==boolean.class||type==Boolean.class){String v=value.trim();if(List.of("是","true","1","在校","在籍").contains(v))converted=true;else if(List.of("否","false","0","不在校","不在籍").contains(v))converted=false;else throw new IllegalArgumentException(title(n)+"应填写是或否");}else if(type==int.class||type==Integer.class)converted=Integer.parseInt(value.trim());else if(type==Date.class)converted=value.isBlank()?null:Date.valueOf(value.trim());else converted=gson.fromJson(gson.toJson(value.trim()),type);setter.invoke(s,converted);}
 private void showReviewDetail(StudentChangeRequest r){selected=r;reviewOverviewPane.setVisible(false);reviewOverviewPane.setManaged(false);reviewDetailPane.setVisible(true);reviewDetailPane.setManaged(true);approveButton.setDisable(false);rejectButton.setDisable(false);long expected=r.getRequestId();service.queryChangeRequest(expected,m->Platform.runLater(()->{if(selected==null||selected.getRequestId()!=expected)return;StudentChangeRequest d=ok(m)?data(m,"request",StudentChangeRequest.class):r;selected=d;reviewItemTable.setItems(FXCollections.observableArrayList(d.getItems()==null?List.of():d.getItems()));}));} @FXML private void handleBackToReviewOverview(){selected=null;reviewItemTable.getItems().clear();reviewRemarkArea.clear();approveButton.setDisable(true);rejectButton.setDisable(true);reviewDetailPane.setVisible(false);reviewDetailPane.setManaged(false);reviewOverviewPane.setVisible(true);reviewOverviewPane.setManaged(true);}
 @FXML private void handleApprove(){review(StudentChangeStatus.APPROVED);}@FXML private void handleReject(){review(StudentChangeStatus.REJECTED);} private void review(StudentChangeStatus s){if(selected==null)return;StudentReviewVO v=new StudentReviewVO();v.setRequestId(selected.getRequestId());v.setReviewResult(s);v.setReviewRemark(safe(reviewRemarkArea.getText()));service.reviewChangeRequest(v,m->Platform.runLater(()->{setStatus(message(m,"审核完成"));if(ok(m)){handleBackToReviewOverview();loadAdmin();}}));}
 private void render(StudentOverviewVO v){Student s=v==null?null:v.getStudent();if(s==null){nameLabel.setText("暂无学籍信息");return;}nameLabel.setText(safe(s.getName()));String initial=nameLabel.getText().isEmpty()?"学":nameLabel.getText().substring(0,1);avatarLabel.setText(initial);sidebarAvatarLabel.setText(initial);sidebarNameLabel.setText(nameLabel.getText());sidebarMajorLabel.setText(show(s.getMajor()));studentMetaLabel.setText(String.join(" · ",List.of(safe(s.getStudentId()),safe(s.getGrade()),safe(s.getCollege()),safe(s.getMajor()))));categoryValue.setText(show(s.getStudentCategory()));statusValue.setText(show(s.getStudentStatus()));gradeValue.setText(show(s.getGrade()));inSchoolValue.setText(s.isInSchool()?"在校":"不在校");pendingHintLabel.setText(v.getPendingRequest()==null?"当前无待审核修改申请":"修改申请审核中，暂不可再次修改");fill(baseInfoGrid,s,baseFields());fill(studyInfoGrid,s,studyFields());fill(admissionInfoGrid,s,admissionFields());fill(contactInfoGrid,s,contactFields());renderAwards(v.getAwards());renderAids(v.getAids());}
 private void renderAwards(List<StudentAward> list){awardTile.getChildren().clear();if(list==null||list.isEmpty()){awardTile.getChildren().add(emptyRecord("暂无奖惩记录"));return;}for(StudentAward a:list)awardTile.getChildren().add(recordCard("🏆",show(a.getAwardName()),joinLine(show(a.getAwardType()),show(a.getAwardLevel())),show(a.getAwardDate()),"award-record-icon"));}
 private void renderAids(List<StudentAid> list){aidTile.getChildren().clear();if(list==null||list.isEmpty()){aidTile.getChildren().add(emptyRecord("暂无资助记录"));return;}for(StudentAid a:list){String amount=a.getAmount()==null?"":("¥"+a.getAmount());aidTile.getChildren().add(recordCard("◉",show(a.getAidName()),joinLine(show(a.getAidType()),amount),show(a.getAidDate()),"aid-record-icon"));}}
 private HBox recordCard(String icon,String name,String meta,String date,String iconStyle){Label badge=new Label(icon);badge.getStyleClass().add(iconStyle);Label title=new Label(name);title.getStyleClass().add("record-title");title.setWrapText(false);Label detail=new Label(meta);detail.getStyleClass().add("record-meta");Label time=new Label(date);time.getStyleClass().add("record-date");VBox textBox=new VBox(3,title,detail,time);HBox card=new HBox(11,badge,textBox);card.setAlignment(Pos.CENTER_LEFT);card.getStyleClass().add("student-record-card");return card;} private HBox emptyRecord(String text){Label l=new Label(text);l.getStyleClass().add("record-empty");HBox box=new HBox(l);box.setAlignment(Pos.CENTER_LEFT);return box;} private String joinLine(String a,String b){if("-".equals(a))return b;if(b==null||b.isBlank()||"-".equals(b))return a;return a+" · "+b;}
 private void fill(GridPane g,Student s,List<String> names){prepareSixColumns(g);g.getChildren().clear();for(int i=0;i<names.size();i++){String n=names.get(i);int[] p=fieldPosition(g,n,i);Label k=new Label(title(n)),v=new Label(show(read(s,n)));styleFieldKey(k);v.getStyleClass().add("student-field-value");v.setAlignment(Pos.CENTER_LEFT);v.setWrapText(true);v.setMinWidth(0);v.setMaxWidth(Double.MAX_VALUE);v.setTextOverrun(OverrunStyle.ELLIPSIS);v.setTooltip(new Tooltip(v.getText()));g.add(k,p[1]*2,p[0]);g.add(v,p[1]*2+1,p[0]);if(fieldSpansRemainder(g,n))GridPane.setColumnSpan(v,5-p[1]*2);}}
 private void styleFieldKey(Label key){key.getStyleClass().add("student-field-key");key.setAlignment(Pos.CENTER_LEFT);key.setWrapText(false);key.setMinWidth(136);key.setPrefWidth(136);key.setMaxWidth(136);key.setTextOverrun(OverrunStyle.ELLIPSIS);key.setTooltip(new Tooltip(key.getText()));}
 private void prepareSixColumns(GridPane g){g.setAlignment(Pos.CENTER_LEFT);g.setHgap(12);g.setVgap(9);g.setMaxWidth(Double.MAX_VALUE);if(g.getColumnConstraints().size()==6)return;g.getColumnConstraints().clear();for(int i=0;i<6;i++){ColumnConstraints c=new ColumnConstraints();if(i%2==0){c.setMinWidth(136);c.setPrefWidth(136);c.setMaxWidth(136);c.setHgrow(Priority.NEVER);}else{c.setMinWidth(0);c.setPrefWidth(150);c.setMaxWidth(Double.MAX_VALUE);c.setHgrow(Priority.ALWAYS);}c.setHalignment(javafx.geometry.HPos.LEFT);c.setValignment(javafx.geometry.VPos.CENTER);c.setFillWidth(true);g.getColumnConstraints().add(c);}}
 private int[] fieldPosition(GridPane g,String n,int index){if(g==baseInfoGrid){return switch(n){case"userId"->new int[]{0,0};case"studentId"->new int[]{0,1};case"name"->new int[]{0,2};case"politicalStatus"->new int[]{1,0};case"nationality"->new int[]{1,1};case"gender"->new int[]{1,2};case"idType"->new int[]{2,0};case"idNumber"->new int[]{2,1};case"idIssueDate"->new int[]{2,2};case"birthDate"->new int[]{3,0};case"nativePlace"->new int[]{3,1};case"householdType"->new int[]{3,2};case"birthPlace"->new int[]{4,0};case"sourcePlace"->new int[]{4,1};case"registeredResidence"->new int[]{5,0};case"leagueMember"->new int[]{6,0};case"leagueJoinDate"->new int[]{6,1};case"partyMember"->new int[]{6,2};case"partyJoinDate"->new int[]{7,0};case"healthStatus"->new int[]{7,1};default->new int[]{index/3,index%3};};}if(g==contactInfoGrid){return switch(n){case"telephone"->new int[]{0,0};case"mobile"->new int[]{0,1};case"email"->new int[]{0,2};case"qq"->new int[]{1,0};case"wechat"->new int[]{1,1};case"campusAddress"->new int[]{2,0};case"emergencyContact"->new int[]{3,0};case"emergencyPhone"->new int[]{3,1};default->new int[]{index/3,index%3};};}return new int[]{index/3,index%3};}
 private boolean fieldSpansRemainder(GridPane g,String n){return(g==baseInfoGrid&&"registeredResidence".equals(n))||(g==contactInfoGrid&&"campusAddress".equals(n));}
 private Object read(Student s,String n){try{String x=Character.toUpperCase(n.charAt(0))+n.substring(1);try{return Student.class.getMethod("get"+x).invoke(s);}catch(NoSuchMethodException e){return Student.class.getMethod("is"+x).invoke(s);}}catch(Exception e){return null;}}
 private String title(String n){return Map.ofEntries(Map.entry("userId","用户"),Map.entry("studentId","学号"),Map.entry("name","姓名"),Map.entry("gender","性别"),Map.entry("politicalStatus","政治面貌"),Map.entry("nationality","民族"),Map.entry("idType","身份证件类型"),Map.entry("idNumber","身份证号"),Map.entry("idIssueDate","身份证签发日期"),Map.entry("birthDate","出生日期"),Map.entry("nativePlace","籍贯"),Map.entry("householdType","户口性质"),Map.entry("birthPlace","出生地"),Map.entry("sourcePlace","生源地"),Map.entry("registeredResidence","户口所在地"),Map.entry("leagueMember","是否团员"),Map.entry("leagueJoinDate","入团时间"),Map.entry("partyMember","是否党员"),Map.entry("partyJoinDate","入党时间"),Map.entry("healthStatus","健康状况"),Map.entry("studentCategory","学生类别"),Map.entry("registered","是否在籍"),Map.entry("inSchool","是否在校"),Map.entry("studentStatus","学籍状态"),Map.entry("campus","校区"),Map.entry("grade","年级"),Map.entry("college","院系"),Map.entry("major","专业"),Map.entry("className","班级"),Map.entry("educationLevel","培养层次"),Map.entry("trainingMode","培养方式"),Map.entry("schoolingLength","学制"),Map.entry("counselorName","辅导员"),Map.entry("counselorPhone","辅导员联系方式"),Map.entry("candidateCategory","考生类别"),Map.entry("admissionDate","入学日期"),Map.entry("admissionMethod","入学方式"),Map.entry("graduationSchool","毕业中学"),Map.entry("middleSchoolClass","中学所在班级"),Map.entry("middleSchoolTeacher","中学班主任姓名"),Map.entry("telephone","联系电话"),Map.entry("mobile","手机号"),Map.entry("email","电子邮箱"),Map.entry("qq","QQ号"),Map.entry("wechat","微信号"),Map.entry("campusAddress","在校地址"),Map.entry("emergencyContact","紧急联系人"),Map.entry("emergencyPhone","紧急联系人联系方式")).getOrDefault(n,n);}
 private boolean ok(Message m){return m!=null&&m.getCode()==MessageCode.SUCCESS;} private String message(Message m,String f){return m!=null&&m.getMessage()!=null&&!m.getMessage().isBlank()?m.getMessage():f;} private SimpleStringProperty text(Object v){return new SimpleStringProperty(show(v));} private String show(Object v){if(v==null||String.valueOf(v).isBlank())return "-";if(v instanceof Boolean)return(Boolean)v?"是":"否";return String.valueOf(v);} private String safe(Object v){return v==null?"":String.valueOf(v).trim();} private String status(StudentChangeStatus s){return s==null?"-":switch(s){case PENDING->"待审核";case APPROVED->"已通过";case REJECTED->"未通过";case CANCELLED->"已取消";};} private void setStatus(String s){if(statusBarLabel!=null)statusBarLabel.setText(s);}
}
