package controller;
import javafx.geometry.Pos;
import app.ClientMain; import com.google.gson.*; import com.google.gson.reflect.TypeToken; import entity.*; import enums.StudentChangeStatus; import javafx.application.Platform; import javafx.beans.property.SimpleStringProperty; import javafx.collections.*; import javafx.concurrent.Task; import javafx.fxml.FXML; import javafx.scene.control.*; import javafx.scene.layout.*; import javafx.stage.FileChooser; import protocol.*; import service.TeacherClientService; import session.ClientSession; import util.AlertUtil; import util.spreadsheet.TeacherExcelExport; import vo.*; import java.io.File; import java.lang.reflect.*; import java.sql.Date; import java.util.*;
public class TeacherController {
 @FXML private util.control.InformationReviewStatusPane reviewStatusPane;
 @FXML private Label nameLabel,metaLabel,statusLabel,avatarLabel,sideAvatarLabel,sideNameLabel,sideMetaLabel,overviewStatusValue,overviewTitleValue,overviewCollegeValue,overviewEmployedValue,selectedTeacherCountLabel,adminWorkspaceTitle; @FXML private GridPane baseGrid,jobGrid,contactGrid; @FXML private Button editButton,jobEditButton,contactEditButton,editExperienceButton,deleteExperienceButton,exportTeachersButton,managementNavButton,maintenanceNavButton; @FXML private TabPane tabs; @FXML private Tab overviewTab,detailTab,experienceTab,adminTab,reviewTab; @FXML private VBox overviewPane,baseSection,jobSection,contactSection,experienceCardContainer; @FXML private Pane detailPane; @FXML private ScrollPane detailScroll; @FXML private TableView<Teacher> teacherTable; @FXML private TableColumn<Teacher,Void> selectCol,actionCol; @FXML private TableColumn<Teacher,String> idCol,nameCol,collegeCol,departmentCol,titleCol,statusCol; @FXML private TableView<TeacherChangeRequest> requestTable; @FXML private TableColumn<TeacherChangeRequest,String> requestTeacherCol,requestSubmitCol,requestStatusCol,requestReviewCol;
 private final TeacherClientService service=new TeacherClientService();private final Gson gson=new Gson();private TeacherOverviewVO overview;private final List<Control> editableControls=new ArrayList<>();private boolean editing,adminMaintenanceMode;private TeacherWorkExperience selectedExperience;private Pane selectedExperienceCard;private List<Teacher> teachers=new ArrayList<>();private final Set<String> selectedTeacherIds=new LinkedHashSet<>();private CheckBox selectAllTeachers;
 private static final List<String> BASE=List.of("UID","teacherId","name","politicalStatus","nationality","gender","idType","idNumber","idIssueDate","birthDate","nativePlace","householdType","birthPlace","sourcePlace","registeredResidence","partyMember","partyJoinDate","healthStatus");
 private static final List<String> JOB=List.of("employed","employmentStatus","campus","college","department","title","position");
 private static final List<String> CONTACT=List.of("telephone","mobile","email","qq","wechat","officeAddress","emergencyContact","emergencyPhone");
 private static final Set<String> EDITABLE=Set.of("politicalStatus","nationality","gender","idType","idNumber","idIssueDate","birthDate","nativePlace","householdType","birthPlace","sourcePlace","registeredResidence","partyMember","partyJoinDate","healthStatus","campus","telephone","mobile","email","qq","wechat","officeAddress","emergencyContact","emergencyPhone");
 @FXML public void initialize(){setupTables();setupActionColumn();boolean admin=isAdmin();reviewStatusPane.setVisible(!admin);reviewStatusPane.setManaged(!admin);if(admin){tabs.getTabs().remove(experienceTab);applyAdminMode();loadAdmin();}else{tabs.getTabs().removeAll(adminTab,reviewTab);service.overview(this::receiveOverview);}}
 @FXML private void back(){ClientMain.switchScene("/resources/fxml/MainView.fxml");} @FXML private void refresh(){if(editing)cancelEdit();if(isAdmin()&&tabs.getSelectionModel().getSelectedItem()==detailTab&&overview!=null&&overview.getTeacher()!=null)service.query(overview.getTeacher().getTeacherId(),this::receiveOverview);else if(isAdmin())loadAdmin();else service.overview(this::receiveOverview);} @FXML private void edit(){beginGlobalEdit();}
 @FXML private void viewDetails(){tabs.getSelectionModel().select(detailTab); }
 @FXML private void viewExperiences(){tabs.getSelectionModel().select(experienceTab);}
 @FXML private void backFromExperiences(){tabs.getSelectionModel().select(overviewTab);}
 @FXML private void selectAdmin(){adminMaintenanceMode=false;applyAdminMode();}
 @FXML private void selectMaintenance(){adminMaintenanceMode=true;applyAdminMode();}
 private void applyAdminMode(){if(!isAdmin())return;tabs.getSelectionModel().select(adminTab);adminWorkspaceTitle.setText(adminMaintenanceMode?"教师信息维护":"教师信息管理");managementNavButton.getStyleClass().removeAll("student-side-button","student-side-button-active");maintenanceNavButton.getStyleClass().removeAll("student-side-button","student-side-button-active");managementNavButton.getStyleClass().add(adminMaintenanceMode?"student-side-button":"student-side-button-active");maintenanceNavButton.getStyleClass().add(adminMaintenanceMode?"student-side-button-active":"student-side-button");teacherTable.refresh();}
 @FXML private void selectReview(){tabs.getSelectionModel().select(reviewTab);}
 @FXML private void returnOverview(){if(editing)cancelEdit();tabs.getSelectionModel().select(isAdmin()?adminTab:overviewTab); }
 @FXML private void showBase(){scrollTo(baseSection);}@FXML private void showJob(){scrollTo(jobSection);}@FXML private void showContact(){scrollTo(contactSection);}
 private void scrollTo(VBox node){if(detailScroll==null||node==null)return;double total=detailScroll.getContent().getBoundsInLocal().getHeight()-detailScroll.getViewportBounds().getHeight();detailScroll.setVvalue(total<=0?0:node.getBoundsInParent().getMinY()/total);}
 private void receiveOverview(Message m){Platform.runLater(()->{if(!ok(m)){statusLabel.setText(m.getMessage());return;}overview=data(m,"overview",TeacherOverviewVO.class);render();});}
 private void render(){TeacherChangeRequest progress=overview==null?null:(overview.getPendingRequest()!=null?overview.getPendingRequest():overview.getLatestRequest());reviewStatusPane.showRequest(progress==null?null:progress.getStatus(),progress==null?null:progress.getSubmitTime());Teacher t=overview==null?null:overview.getTeacher();if(t==null){statusLabel.setText("暂无教师档案");return;}String name=show(t.getName()),initial="-".equals(name)?"师":name.substring(0,1);nameLabel.setText(name);avatarLabel.setText(initial);sideAvatarLabel.setText(initial);sideNameLabel.setText(name);sideMetaLabel.setText(show(t.getDepartment()));metaLabel.setText(String.join(" · ",show(t.getTeacherId()),show(t.getCollege()),show(t.getDepartment()),show(t.getTitle())));overviewStatusValue.setText(show(t.getEmploymentStatus()));overviewTitleValue.setText(show(t.getTitle()));overviewCollegeValue.setText(show(t.getCollege()));overviewEmployedValue.setText(t.isEmployed()?"在职":"离职");fill(baseGrid,t,BASE);fill(jobGrid,t,JOB);fill(contactGrid,t,CONTACT);renderExperiences(overview.getWorkExperiences());if(isAdmin())setDetailEditable(adminMaintenanceMode);statusLabel.setText(overview.getPendingRequest()==null?"教师信息已更新":"修改申请待管理员审核");}
 private void renderExperiences(List<TeacherWorkExperience> records){if(experienceCardContainer==null)return;selectedExperience=null;selectedExperienceCard=null;editExperienceButton.setDisable(true);deleteExperienceButton.setDisable(true);experienceCardContainer.getChildren().clear();if(records==null||records.isEmpty()){Label empty=new Label("暂无工作经历");empty.getStyleClass().add("student-info-empty-card");empty.setMaxWidth(Double.MAX_VALUE);experienceCardContainer.getChildren().add(empty);return;}for(TeacherWorkExperience record:records){GridPane grid=new GridPane();grid.getStyleClass().add("student-info-record-grid");grid.setMaxWidth(Double.MAX_VALUE);addCardField(grid,"开始年月",month(record.getStartDate()),0,0);addCardField(grid,"结束年月",record.getEndDate()==null?"至今":month(record.getEndDate()),0,1);addCardField(grid,"工作单位",record.getOrganization(),1,0);addCardField(grid,"所在部门",record.getDepartment(),1,1);addCardField(grid,"职务",record.getPosition(),2,0);addCardField(grid,"工作内容",record.getDescription(),2,1);VBox card=new VBox(grid);card.getStyleClass().add("student-info-record-card");card.setMaxWidth(Double.MAX_VALUE);card.setOnMouseClicked(event->selectExperience(record,card));experienceCardContainer.getChildren().add(card);}}
 private void addCardField(GridPane grid,String key,Object value,int row,int pair){Label k=new Label(key),v=new Label(show(value));k.getStyleClass().add("student-field-key");v.getStyleClass().add("student-field-value");v.setWrapText(true);v.setMaxWidth(Double.MAX_VALUE);grid.add(k,pair*2,row);grid.add(v,pair*2+1,row);ColumnConstraints a=new ColumnConstraints(120),b=new ColumnConstraints();if(grid.getColumnConstraints().isEmpty()){b.setHgrow(Priority.ALWAYS);grid.getColumnConstraints().addAll(a,b,new ColumnConstraints(120),new ColumnConstraints());grid.getColumnConstraints().get(3).setHgrow(Priority.ALWAYS);}}
 private void selectExperience(TeacherWorkExperience record,Pane card){if(selectedExperienceCard!=null)selectedExperienceCard.getStyleClass().remove("student-info-record-card-selected");selectedExperience=record;selectedExperienceCard=card;card.getStyleClass().add("student-info-record-card-selected");editExperienceButton.setDisable(false);deleteExperienceButton.setDisable(false);}
 private void fill(GridPane g,Teacher t,List<String> fields){prepareSixColumns(g);g.getChildren().clear();for(int i=0;i<fields.size();i++){String f=fields.get(i);Label k=new Label(title(f)),v=new Label(show(read(t,f)));k.getStyleClass().add("student-field-key");k.setAlignment(Pos.CENTER_LEFT);k.setMinWidth(136);k.setPrefWidth(136);k.setMaxWidth(136);k.setTooltip(new Tooltip(k.getText()));v.getStyleClass().add("student-field-value");v.setAlignment(Pos.CENTER_LEFT);v.setWrapText(true);v.setMinWidth(0);v.setMaxWidth(Double.MAX_VALUE);v.setTooltip(new Tooltip(v.getText()));int row=i/3,pair=i%3;g.add(k,pair*2,row);g.add(v,pair*2+1,row);}}
 private void beginGlobalEdit(){if(editing||overview==null||overview.getTeacher()==null)return;if(!isAdmin()&&overview.getPendingRequest()!=null){statusLabel.setText("当前修改申请正在审核中，审核完成后才能再次修改");return;}editableControls.clear();editing=true;fillEditable(baseGrid,BASE);fillEditable(jobGrid,JOB);fillEditable(contactGrid,CONTACT);Button cancel=new Button("取消");cancel.getStyleClass().add("btn-secondary");cancel.setOnAction(e->cancelEdit());Button submit=new Button(isAdmin()?"保存修改":"提交修改申请");submit.getStyleClass().add("btn-primary");submit.setOnAction(e->submitEdit());HBox actions=new HBox(8,cancel,submit);actions.setAlignment(Pos.CENTER_RIGHT);contactGrid.add(actions,0,(CONTACT.size()+2)/3,6,1);statusLabel.setText(isAdmin()?"全部信息已进入编辑状态，保存后直接生效":"全部信息已进入编辑状态，提交后等待审核");}
 private void fillEditable(GridPane grid,List<String> fields){prepareSixColumns(grid);grid.getChildren().clear();Teacher teacher=overview.getTeacher();for(int i=0;i<fields.size();i++){String field=fields.get(i);Label key=new Label(title(field));key.getStyleClass().add("student-field-key");key.setAlignment(Pos.CENTER_LEFT);key.setMinWidth(136);key.setPrefWidth(136);key.setMaxWidth(136);Control value=createEditor(field,showInput(read(teacher,field)));value.setUserData(field);value.setMinWidth(0);value.setMaxWidth(Double.MAX_VALUE);boolean allowed=isAdmin()||EDITABLE.contains(field);value.setDisable(!allowed);if(allowed)editableControls.add(value);int row=i/3,pair=i%3;grid.add(key,pair*2,row);grid.add(value,pair*2+1,row);}}
 private Control createEditor(String field,String initial){Control control;if(Set.of("idIssueDate","birthDate","partyJoinDate").contains(field)){DatePicker picker=new DatePicker();if(!initial.isBlank())try{picker.setValue(java.time.LocalDate.parse(initial));}catch(Exception ignored){}control=picker;}else if("idType".equals(field)){ComboBox<String> combo=new ComboBox<>(FXCollections.observableArrayList("居民身份证","港澳台居民居住证","护照","其他"));combo.setValue(initial);control=combo;}else if("householdType".equals(field)){ComboBox<String> combo=new ComboBox<>(FXCollections.observableArrayList("城镇户口","农村居民户口","集体户口","其他"));combo.setValue(initial);control=combo;}else if(Set.of("partyMember","employed").contains(field)){ComboBox<String> combo=new ComboBox<>(FXCollections.observableArrayList("是","否"));combo.setValue(Set.of("true","1","是","在职").contains(initial)?"是":"否");control=combo;}else control=new TextField(initial);control.getStyleClass().add("form-control");return control;}
 private String controlValue(Control control){if(control instanceof TextInputControl text)return text.getText().trim();if(control instanceof DatePicker date)return date.getValue()==null?"":date.getValue().toString();if(control instanceof ComboBox<?> combo)return combo.getValue()==null?"":String.valueOf(combo.getValue()).trim();return "";}
 private void cancelEdit(){editing=false;editableControls.clear();render();statusLabel.setText("已取消编辑");}
 private void submitEdit(){Teacher teacher=overview.getTeacher();Map<String,String> changed=new LinkedHashMap<>();for(Control control:editableControls){String field=String.valueOf(control.getUserData()),old=showInput(read(teacher,field)),now=controlValue(control);if(!old.equals(now))changed.put(field,now);}if(changed.isEmpty()){statusLabel.setText("没有检测到修改内容");return;}if(isAdmin()){Teacher updated=gson.fromJson(gson.toJson(teacher),Teacher.class);try{changed.forEach((field,value)->write(updated,field,value));}catch(Exception exception){statusLabel.setText("格式错误: "+exception.getMessage());return;}service.update(updated,m->Platform.runLater(()->{statusLabel.setText(m.getMessage());if(ok(m)){editing=false;service.query(updated.getTeacherId(),this::receiveOverview);}}));}else submitChanges(teacher,changed);}
 private void prepareSixColumns(GridPane g){g.setAlignment(Pos.CENTER_LEFT);g.setHgap(12);g.setVgap(9);g.setMaxWidth(Double.MAX_VALUE);if(g.getColumnConstraints().size()==6)return;g.getColumnConstraints().clear();for(int i=0;i<6;i++){ColumnConstraints c=new ColumnConstraints();if(i%2==0){c.setMinWidth(136);c.setPrefWidth(136);c.setMaxWidth(136);c.setHgrow(Priority.NEVER);}else{c.setMinWidth(0);c.setPrefWidth(150);c.setMaxWidth(Double.MAX_VALUE);c.setHgrow(Priority.ALWAYS);}c.setFillWidth(true);g.getColumnConstraints().add(c);}}
 private void setupTables(){selectAllTeachers=new CheckBox();selectAllTeachers.setOnAction(e->{if(selectAllTeachers.isSelected())for(Teacher teacher:teacherTable.getItems())selectedTeacherIds.add(teacher.getTeacherId());else for(Teacher teacher:teacherTable.getItems())selectedTeacherIds.remove(teacher.getTeacherId());teacherTable.refresh();updateTeacherSelection();});selectCol.setGraphic(selectAllTeachers);selectCol.setCellFactory(column->new TableCell<>(){private final CheckBox checkBox=new CheckBox();{setAlignment(Pos.CENTER);checkBox.setOnAction(e->{Teacher teacher=getTableView().getItems().get(getIndex());if(checkBox.isSelected())selectedTeacherIds.add(teacher.getTeacherId());else selectedTeacherIds.remove(teacher.getTeacherId());updateTeacherSelection();});}@Override protected void updateItem(Void item,boolean empty){super.updateItem(item,empty);if(empty||getIndex()>=getTableView().getItems().size())setGraphic(null);else{checkBox.setSelected(selectedTeacherIds.contains(getTableView().getItems().get(getIndex()).getTeacherId()));setGraphic(checkBox);}}});idCol.setCellValueFactory(c->s(c.getValue().getTeacherId()));nameCol.setCellValueFactory(c->s(c.getValue().getName()));collegeCol.setCellValueFactory(c->s(c.getValue().getCollege()));departmentCol.setCellValueFactory(c->s(c.getValue().getDepartment()));titleCol.setCellValueFactory(c->s(c.getValue().getTitle()));statusCol.setCellValueFactory(c->s(c.getValue().getEmploymentStatus()));teacherTable.setOnMouseClicked(e->{if(e.getClickCount()==2){Teacher t=teacherTable.getSelectionModel().getSelectedItem();if(t!=null)service.query(t.getTeacherId(),m->Platform.runLater(()->{if(ok(m)){overview=data(m,"overview",TeacherOverviewVO.class);render();tabs.getSelectionModel().select(detailTab);}else statusLabel.setText(m.getMessage());}));}});requestTeacherCol.setCellValueFactory(c->s(c.getValue().getTeacherId()));requestSubmitCol.setCellValueFactory(c->s(c.getValue().getSubmitTime()));requestStatusCol.setCellValueFactory(c->s(c.getValue().getStatus()));requestReviewCol.setCellValueFactory(c->s(c.getValue().getReviewTime()));requestTable.setOnMouseClicked(e->{if(e.getClickCount()==2)reviewSelected();});}
 private void setupActionColumn(){actionCol.setCellFactory(column->new TableCell<>(){private final Button button=new Button();{button.getStyleClass().add("table-action-button");button.setOnAction(e->{Teacher teacher=getTableView().getItems().get(getIndex());service.query(teacher.getTeacherId(),m->Platform.runLater(()->{if(!ok(m)){statusLabel.setText(m.getMessage());return;}overview=data(m,"overview",TeacherOverviewVO.class);render();tabs.getSelectionModel().select(detailTab);}));});}@Override protected void updateItem(Void item,boolean empty){super.updateItem(item,empty);button.setText(adminMaintenanceMode?"编辑":"查看详情");setGraphic(empty?null:button);}});}
 private void setDetailEditable(boolean visible){for(Button button:List.of(editButton,jobEditButton,contactEditButton)){button.setVisible(visible);button.setManaged(visible);}}
 private void loadAdmin(){service.list(m->Platform.runLater(()->{if(ok(m)){List<Teacher> x=data(m,"teachers",new TypeToken<List<Teacher>>(){}.getType());teachers=x==null?new ArrayList<>():new ArrayList<>(x);selectedTeacherIds.clear();teacherTable.setItems(FXCollections.observableArrayList(teachers));updateTeacherSelection();}}));service.reviews(m->Platform.runLater(()->{if(ok(m)){List<TeacherChangeRequest>x=data(m,"requests",new TypeToken<List<TeacherChangeRequest>>(){}.getType());requestTable.setItems(FXCollections.observableArrayList(x==null?List.of():x));}}));}
 private void updateTeacherSelection(){if(selectAllTeachers!=null){long count=teacherTable.getItems().stream().filter(t->selectedTeacherIds.contains(t.getTeacherId())).count();selectAllTeachers.setIndeterminate(count>0&&count<teacherTable.getItems().size());selectAllTeachers.setSelected(!teacherTable.getItems().isEmpty()&&count==teacherTable.getItems().size());}if(selectedTeacherCountLabel!=null)selectedTeacherCountLabel.setText("已选择 "+selectedTeacherIds.size()+" 人");if(exportTeachersButton!=null)exportTeachersButton.setDisable(selectedTeacherIds.isEmpty());}
 @FXML private void exportSelectedTeachers(){List<Teacher> selected=teachers.stream().filter(t->selectedTeacherIds.contains(t.getTeacherId())).toList();if(selected.isEmpty()){AlertUtil.showWarning("请选择教师","请先勾选需要导出的教师。");return;}FileChooser chooser=new FileChooser();chooser.setTitle("导出教师信息");chooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("Excel 工作簿 (*.xlsx)","*.xlsx"));chooser.setInitialFileName("教师信息_"+java.time.LocalDate.now()+".xlsx");File chosen=chooser.showSaveDialog(teacherTable.getScene().getWindow());if(chosen==null)return;File output=chosen.getName().toLowerCase(Locale.ROOT).endsWith(".xlsx")?chosen:new File(chosen.getParentFile(),chosen.getName()+".xlsx");exportTeachersButton.setDisable(true);statusLabel.setText("正在导出 "+selected.size()+" 名教师的信息...");Task<Void> task=new Task<>(){@Override protected Void call()throws Exception{TeacherExcelExport.export(selected,output);return null;}};task.setOnSucceeded(e->{exportTeachersButton.setDisable(false);statusLabel.setText("已导出 "+selected.size()+" 名教师的信息");AlertUtil.showInfo("导出成功","Excel 已保存至：\n"+output.getAbsolutePath());});task.setOnFailed(e->{exportTeachersButton.setDisable(false);statusLabel.setText("教师信息导出失败");Throwable error=task.getException();AlertUtil.showError("导出失败",error==null?"无法生成 Excel 文件。":"无法生成 Excel 文件：\n"+error.getMessage());});Thread worker=new Thread(task,"teacher-excel-export");worker.setDaemon(true);worker.start();}
 @FXML private void reviewSelected(){TeacherChangeRequest r=requestTable.getSelectionModel().getSelectedItem();if(r==null||r.getStatus()!=StudentChangeStatus.PENDING)return;Alert a=new Alert(Alert.AlertType.CONFIRMATION,"请选择审核结果",new ButtonType("通过"),new ButtonType("不通过"),ButtonType.CANCEL);a.showAndWait().ifPresent(b->{if(b==ButtonType.CANCEL)return;TeacherReviewVO v=new TeacherReviewVO();v.setRequestId(r.getRequestId());v.setReviewResult("通过".equals(b.getText())?StudentChangeStatus.APPROVED:StudentChangeStatus.REJECTED);service.review(v,m->Platform.runLater(this::loadAdmin));});}
 @FXML private void addWorkExperience(){showWorkExperienceEditor(null);}
 @FXML private void editWorkExperience(){if(selectedExperience==null){statusLabel.setText("请先选择工作经历");return;}showWorkExperienceEditor(selectedExperience);}
 @FXML private void deleteWorkExperience(){if(selectedExperience==null){statusLabel.setText("请先选择工作经历");return;}Alert alert=new Alert(Alert.AlertType.CONFIRMATION,"确定删除选中的工作经历吗？",ButtonType.OK,ButtonType.CANCEL);alert.setHeaderText(null);if(alert.showAndWait().orElse(ButtonType.CANCEL)!=ButtonType.OK)return;service.deleteWorkExperience(selectedExperience.getExperienceId(),m->Platform.runLater(()->{statusLabel.setText(m.getMessage());if(ok(m))service.overview(this::receiveOverview);}));}
 private void showWorkExperienceEditor(TeacherWorkExperience source){Dialog<ButtonType> dialog=new Dialog<>();dialog.setTitle(source==null?"新增工作经历":"编辑工作经历");GridPane grid=new GridPane();grid.setHgap(12);grid.setVgap(10);grid.setPadding(new javafx.geometry.Insets(8,12,8,12));DatePicker start=new DatePicker(),end=new DatePicker();TextField organization=new TextField(),department=new TextField(),position=new TextField(),description=new TextField();if(source!=null){if(source.getStartDate()!=null)start.setValue(source.getStartDate().toLocalDate());if(source.getEndDate()!=null)end.setValue(source.getEndDate().toLocalDate());organization.setText(input(source.getOrganization()));department.setText(input(source.getDepartment()));position.setText(input(source.getPosition()));description.setText(input(source.getDescription()));}start.setPromptText("必填");end.setPromptText("留空表示至今");Control[] controls={start,end,organization,department,position,description};String[] labels={"开始时间 *","结束时间","工作单位 *","所在部门","职务 *","工作内容"};for(int i=0;i<labels.length;i++){controls[i].setPrefWidth(360);grid.add(new Label(labels[i]),0,i);grid.add(controls[i],1,i);}dialog.getDialogPane().setContent(grid);dialog.getDialogPane().getButtonTypes().addAll(ButtonType.OK,ButtonType.CANCEL);dialog.showAndWait().ifPresent(button->{if(button!=ButtonType.OK)return;try{if(start.getValue()==null)throw new IllegalArgumentException("开始时间不能为空");if(organization.getText().isBlank())throw new IllegalArgumentException("工作单位不能为空");if(position.getText().isBlank())throw new IllegalArgumentException("职务不能为空");if(end.getValue()!=null&&end.getValue().isBefore(start.getValue()))throw new IllegalArgumentException("结束时间不能早于开始时间");TeacherWorkExperience value=source==null?new TeacherWorkExperience():gson.fromJson(gson.toJson(source),TeacherWorkExperience.class);value.setStartDate(Date.valueOf(start.getValue()));value.setEndDate(end.getValue()==null?null:Date.valueOf(end.getValue()));value.setOrganization(organization.getText().trim());value.setDepartment(department.getText().trim());value.setPosition(position.getText().trim());value.setDescription(description.getText().trim());java.util.function.Consumer<Message> done=m->Platform.runLater(()->{statusLabel.setText(m.getMessage());if(ok(m))service.overview(this::receiveOverview);});if(source==null)service.addWorkExperience(value,done);else service.updateWorkExperience(value,done);}catch(Exception exception){statusLabel.setText("工作经历格式错误: "+exception.getMessage());}});}
 private String month(Date value){return value==null?"":value.toString().substring(0,7);}private String input(Object value){return value==null?"":String.valueOf(value);}
 private void submitChanges(Teacher t,Map<String,String> changed){TeacherChangeRequest request=new TeacherChangeRequest();List<TeacherChangeItem> items=new ArrayList<>();changed.forEach((field,value)->{TeacherChangeItem item=new TeacherChangeItem();item.setFieldName(field);item.setOldValue(showInput(read(t,field)));item.setNewValue(value);items.add(item);});request.setItems(items);service.submit(request,m->Platform.runLater(()->{statusLabel.setText(m.getMessage());if(ok(m)){editing=false;service.overview(this::receiveOverview);}}));}
 private boolean isAdmin(){String r=ClientSession.getInstance().getRole();return "ADMIN".equalsIgnoreCase(r)||"管理员".equals(r);} private boolean ok(Message m){return m!=null&&m.getCode()==MessageCode.SUCCESS;} private<T>T data(Message m,String k,Type t){return gson.fromJson(gson.toJson(m.getData().get(k)),t);} private SimpleStringProperty s(Object v){return new SimpleStringProperty(show(v));}
 private Object read(Teacher t,String f){try{String x=Character.toUpperCase(f.charAt(0))+f.substring(1);try{return Teacher.class.getMethod("get"+x).invoke(t);}catch(NoSuchMethodException e){return Teacher.class.getMethod("is"+x).invoke(t);}}catch(Exception e){return null;}}
 private void write(Teacher t,String f,String v){try{Field field=Teacher.class.getDeclaredField(f);String x=Character.toUpperCase(f.charAt(0))+f.substring(1);Method m=Arrays.stream(Teacher.class.getMethods()).filter(z->z.getName().equals("set"+x)).findFirst().orElseThrow();Object q=field.getType()==boolean.class?Set.of("是","true","1","在职").contains(v):field.getType()==Date.class?(v.isBlank()?null:Date.valueOf(v)):v.trim();m.invoke(t,q);}catch(Exception e){throw new IllegalArgumentException(f);}}
 private List<String> concat(List<String>...xs){List<String>o=new ArrayList<>();for(List<String>x:xs)o.addAll(x);return o;} private String show(Object v){if(v==null||String.valueOf(v).isBlank())return "-";return v instanceof Boolean?((Boolean)v?"是":"否"):String.valueOf(v);}private String showInput(Object v){if(v==null)return "";return v instanceof Boolean?((Boolean)v?"是":"否"):String.valueOf(v);}
 private String title(String f){return Map.ofEntries(Map.entry("UID","用户名"),Map.entry("teacherId","工号"),Map.entry("name","姓名"),Map.entry("politicalStatus","政治面貌"),Map.entry("nationality","民族"),Map.entry("gender","性别"),Map.entry("idType","身份证件类型"),Map.entry("idNumber","身份证号"),Map.entry("idIssueDate","身份证签发日期"),Map.entry("birthDate","出生日期"),Map.entry("nativePlace","籍贯"),Map.entry("householdType","户口性质"),Map.entry("birthPlace","出生地"),Map.entry("sourcePlace","生源地"),Map.entry("registeredResidence","户口所在地"),Map.entry("partyMember","是否党员"),Map.entry("partyJoinDate","入党时间"),Map.entry("healthStatus","健康状况"),Map.entry("employed","是否在职"),Map.entry("employmentStatus","任职状态"),Map.entry("campus","校区"),Map.entry("college","学院"),Map.entry("department","部门"),Map.entry("title","职称"),Map.entry("position","职务"),Map.entry("telephone","联系电话"),Map.entry("mobile","手机号"),Map.entry("email","电子邮箱"),Map.entry("qq","QQ号"),Map.entry("wechat","微信号"),Map.entry("officeAddress","在校办公地址"),Map.entry("emergencyContact","紧急联系人"),Map.entry("emergencyPhone","紧急联系人联系方式")).getOrDefault(f,f);}
}




