package controller;
import javafx.geometry.Pos;
import app.ClientMain; import com.google.gson.*; import com.google.gson.reflect.TypeToken; import entity.*; import enums.StudentChangeStatus; import javafx.application.Platform; import javafx.beans.property.SimpleStringProperty; import javafx.collections.*; import javafx.concurrent.Task; import javafx.fxml.FXML; import javafx.scene.control.*; import javafx.scene.layout.*; import javafx.stage.FileChooser; import protocol.*; import service.TeacherClientService; import session.ClientSession; import util.AlertUtil; import util.spreadsheet.TeacherExcelExport; import vo.*; import java.io.File; import java.lang.reflect.*; import java.sql.Date; import java.util.*;
public class TeacherController {
 @FXML private TableColumn<TeacherChangeRequest,String> requestNameCol;
 @FXML private TableColumn<TeacherChangeRequest,TeacherChangeRequest> requestActionCol;
 @FXML private Label reviewPageSummary;
 @FXML private TextField teacherReviewSearchIdField,teacherReviewSearchStatusField;
 private int reviewPage=1;
 private List<TeacherChangeRequest> reviewFiltered=List.of();
 private Tab reviewDetailTab;
 private long reviewLoadGeneration;
 @FXML private void previousReviewPage(){if(reviewPage>1)reviewPage--;renderReviewPage();}
 @FXML private void nextReviewPage(){if(reviewPage*20<reviewFiltered.size())reviewPage++;renderReviewPage();}
 private void renderReviewPage(){int pages=Math.max(1,(reviewFiltered.size()+19)/20);reviewPage=Math.max(1,Math.min(reviewPage,pages));int from=Math.min((reviewPage-1)*20,reviewFiltered.size());requestTable.setItems(FXCollections.observableArrayList(reviewFiltered.subList(from,Math.min(from+20,reviewFiltered.size()))));reviewPageSummary.setText("共"+reviewFiltered.size()+"条  第"+reviewPage+" / "+pages+"页");}
 private String reviewStatusText(StudentChangeStatus value){return value==null?"-":switch(value){case PENDING->"待审核";case APPROVED->"已通过";case REJECTED->"未通过";default->"已取消";};}

 @FXML private VBox detailExperienceCards,detailFamilyCards;
 private Teacher displayedTeacher(){if(overview==null||overview.getTeacher()==null)return null;Teacher copy=gson.fromJson(gson.toJson(overview.getTeacher()),Teacher.class);TeacherChangeRequest pending=overview.getPendingRequest();if(pending!=null&&pending.getStatus()==StudentChangeStatus.PENDING&&pending.getItems()!=null)for(TeacherChangeItem item:pending.getItems())if(EDITABLE.contains(item.getFieldName()))write(copy,item.getFieldName(),item.getNewValue()==null?"":item.getNewValue());return copy;}
 @FXML private ToggleButton unfinishedReviewButton,completedReviewButton;
 private boolean showCompletedReviews;
 private List<TeacherChangeRequest> reviewRequests=new ArrayList<>();
 @FXML private void showUnfinishedReviews(){showCompletedReviews=false;applyReviewBucket();}
 @FXML private void showCompletedReviews(){showCompletedReviews=true;applyReviewBucket();}
 private void applyReviewBucket(){
  unfinishedReviewButton.setSelected(!showCompletedReviews);completedReviewButton.setSelected(showCompletedReviews);
  requestReviewCol.setVisible(showCompletedReviews);
  reviewFiltered=reviewRequests.stream().filter(r->show(r.getTeacherId()).toLowerCase(java.util.Locale.ROOT).contains(teacherReviewSearchIdField.getText().trim().toLowerCase(java.util.Locale.ROOT))).filter(r->reviewStatusText(r.getStatus()).contains(teacherReviewSearchStatusField.getText().trim())||r.getStatus().name().equalsIgnoreCase(teacherReviewSearchStatusField.getText().trim())).filter(r->showCompletedReviews?r.getStatus()!=StudentChangeStatus.PENDING:r.getStatus()==StudentChangeStatus.PENDING).toList();reviewPage=1;renderReviewPage();
 }
 @FXML private Button exportPdfButton;
 @FXML private VBox familyCardContainer;
 @FXML private Button editFamilyButton,deleteFamilyButton;
 private TeacherFamilyMember selectedFamilyMember;
 private Pane selectedFamilyCard;
 @FXML private ComboBox<String> switchInformationSelector;
 @FXML private util.control.InformationReviewStatusPane reviewStatusPane;
 @FXML private Label nameLabel,metaLabel,statusLabel,avatarLabel,sideAvatarLabel,sideNameLabel,sideMetaLabel,overviewStatusValue,overviewTitleValue,overviewCollegeValue,overviewEmployedValue,selectedTeacherCountLabel,adminWorkspaceTitle; @FXML private GridPane baseGrid,jobGrid,contactGrid; @FXML private Button editButton,jobEditButton,contactEditButton,editExperienceButton,deleteExperienceButton,exportTeachersButton,managementNavButton,maintenanceNavButton; @FXML private TabPane tabs; @FXML private Tab overviewTab,detailTab,experienceTab,adminTab,reviewTab; @FXML private VBox overviewPane,baseSection,jobSection,contactSection,experienceCardContainer; @FXML private Pane detailPane; @FXML private ScrollPane detailScroll; @FXML private TableView<Teacher> teacherTable; @FXML private TableColumn<Teacher,Void> selectCol; @FXML private TableColumn<Teacher,Teacher> actionCol; @FXML private TableColumn<Teacher,String> idCol,nameCol,collegeCol,departmentCol,titleCol,statusCol; @FXML private TableView<TeacherChangeRequest> requestTable; @FXML private TableColumn<TeacherChangeRequest,String> requestTeacherCol,requestSubmitCol,requestStatusCol,requestReviewCol;
 private final TeacherClientService service=new TeacherClientService();private final Gson gson=new Gson();private TeacherOverviewVO overview;private final List<Control> editableControls=new ArrayList<>();private boolean editing,adminMaintenanceMode;private TeacherWorkExperience selectedExperience;private Pane selectedExperienceCard;private List<Teacher> teachers=new ArrayList<>();private final Set<String> selectedTeacherIds=new LinkedHashSet<>();private CheckBox selectAllTeachers;
 private static final List<String> BASE=List.of("UID","teacherId","name","politicalStatus","nationality","gender","idType","idNumber","idIssueDate","birthDate","nativePlace","householdType","birthPlace","sourcePlace","registeredResidence","partyMember","partyJoinDate","healthStatus");
 private static final List<String> JOB=List.of("employed","employmentStatus","campus","college","department","title","position","education","employmentStartDate");
 private static final List<String> CONTACT=List.of("telephone","mobile","email","qq","wechat","officeAddress","emergencyContact","emergencyPhone");
 private static final Set<String> EDITABLE=Set.of("politicalStatus","nationality","gender","idType","idNumber","idIssueDate","birthDate","nativePlace","householdType","birthPlace","sourcePlace","registeredResidence","partyMember","partyJoinDate","healthStatus","education","employmentStartDate","campus","telephone","mobile","email","qq","wechat","officeAddress","emergencyContact","emergencyPhone");
 @FXML public void initialize(){setupTables();applyReviewBucket();setupActionColumn();boolean admin=isAdmin();switchInformationSelector.getItems().setAll("学生信息","教师信息");switchInformationSelector.setValue("教师信息");switchInformationSelector.setVisible(admin);switchInformationSelector.setManaged(admin);reviewStatusPane.setVisible(!admin);reviewStatusPane.setManaged(!admin);if(admin){tabs.getTabs().remove(experienceTab);applyAdminMode();loadAdmin();}else{tabs.getTabs().removeAll(adminTab,reviewTab);service.overview(this::receiveOverview);}}
 @FXML private void switchToStudents(){if(!isAdmin()||!"学生信息".equals(switchInformationSelector.getValue()))return;ClientMain.switchScene("/resources/fxml/StudentView.fxml");}
 @FXML private void back(){ClientMain.switchScene("/resources/fxml/MainView.fxml");} @FXML private void refresh(){if(editing)cancelEdit();if(isAdmin()&&tabs.getSelectionModel().getSelectedItem()==detailTab&&overview!=null&&overview.getTeacher()!=null)service.query(overview.getTeacher().getTeacherId(),this::receiveOverview);else if(isAdmin())loadAdmin();else service.overview(this::receiveOverview);} @FXML private void edit(){beginGlobalEdit();}
 @FXML private void viewDetails(){tabs.getSelectionModel().select(detailTab); }
 @FXML private void viewExperiences(){tabs.getSelectionModel().select(experienceTab);}
 @FXML private void backFromExperiences(){tabs.getSelectionModel().select(overviewTab);}
 @FXML private void selectAdmin(){adminMaintenanceMode=false;applyAdminMode();}
 @FXML private void selectMaintenance(){adminMaintenanceMode=true;applyAdminMode();}
 private void applyAdminMode(){if(!isAdmin())return;tabs.getSelectionModel().select(adminTab);adminWorkspaceTitle.setText(adminMaintenanceMode?"教师信息维护":"教师信息管理");managementNavButton.getStyleClass().removeAll("student-side-button","student-side-button-active");maintenanceNavButton.getStyleClass().removeAll("student-side-button","student-side-button-active");managementNavButton.getStyleClass().add(adminMaintenanceMode?"student-side-button":"student-side-button-active");maintenanceNavButton.getStyleClass().add(adminMaintenanceMode?"student-side-button-active":"student-side-button");teacherTable.refresh();}
 @FXML private void selectReview(){tabs.getSelectionModel().select(reviewTab);}
 @FXML private void returnOverview(){if(editing)cancelEdit();tabs.getSelectionModel().select(isAdmin()?adminTab:overviewTab); }
 @FXML private void showBase(){scrollTo(baseSection);}@FXML private void showJob(){scrollTo(jobSection);}@FXML private void showContact(){scrollTo(contactSection);}
 private void scrollTo(VBox node){if(detailScroll==null||node==null)return;double total=detailScroll.getContent().getBoundsInLocal().getHeight()-detailScroll.getViewportBounds().getHeight();detailScroll.setVvalue(total<=0?0:node.getBoundsInParent().getMinY()/total);}
 private void receiveOverview(Message m){Platform.runLater(()->{if(!ok(m)){statusLabel.setText(m.getMessage());return;}overview=data(m,"overview",TeacherOverviewVO.class);render();});}
 private void render(){TeacherChangeRequest progress=overview==null?null:(overview.getPendingRequest()!=null?overview.getPendingRequest():overview.getLatestRequest());reviewStatusPane.showRequest(progress==null?null:progress.getStatus(),progress==null?null:progress.getSubmitTime());Teacher t=displayedTeacher();if(t==null){statusLabel.setText("暂无教师档案");return;}String name=show(t.getName()),initial="-".equals(name)?"师":name.substring(0,1);nameLabel.setText(name);avatarLabel.setText(initial);sideAvatarLabel.setText(initial);sideNameLabel.setText(name);sideMetaLabel.setText(show(t.getDepartment()));metaLabel.setText(String.join(" · ",show(t.getTeacherId()),show(t.getCollege()),show(t.getDepartment()),show(t.getTitle())));overviewStatusValue.setText(show(t.getEmploymentStatus()));overviewTitleValue.setText(show(t.getTitle()));overviewCollegeValue.setText(show(t.getCollege()));overviewEmployedValue.setText(t.isEmployed()?"在职":"离职");fill(baseGrid,t,BASE);fill(jobGrid,t,JOB);fill(contactGrid,t,CONTACT);renderExperiences(overview.getWorkExperiences());renderFamilyMembers(overview.getFamilyMembers());renderExperiences(overview.getWorkExperiences(),detailExperienceCards,false);renderFamilyMembers(overview.getFamilyMembers(),detailFamilyCards,false);if(isAdmin())setDetailEditable(adminMaintenanceMode);statusLabel.setText(overview.getPendingRequest()==null?"教师信息已更新":"修改申请待管理员审核");}
 private void renderExperiences(List<TeacherWorkExperience> records){renderExperiences(records,experienceCardContainer,true);}
 private void renderExperiences(List<TeacherWorkExperience> records,VBox experienceCardContainer,boolean selectable){if(experienceCardContainer==null)return;selectedExperience=null;selectedExperienceCard=null;editExperienceButton.setDisable(true);deleteExperienceButton.setDisable(true);experienceCardContainer.getChildren().clear();if(records==null||records.isEmpty()){Label empty=new Label("暂无工作经历");empty.getStyleClass().add("student-info-empty-card");empty.setMaxWidth(Double.MAX_VALUE);experienceCardContainer.getChildren().add(empty);return;}for(TeacherWorkExperience record:records){GridPane grid=new GridPane();grid.getStyleClass().add("student-info-record-grid");grid.setMaxWidth(Double.MAX_VALUE);addCardField(grid,"开始年月",month(record.getStartDate()),0,0);addCardField(grid,"结束年月",record.getEndDate()==null?"至今":month(record.getEndDate()),0,1);addCardField(grid,"工作单位",record.getOrganization(),1,0);addCardField(grid,"所在部门",record.getDepartment(),1,1);addCardField(grid,"职务",record.getPosition(),2,0);addCardField(grid,"工作内容",record.getDescription(),2,1);VBox card=new VBox(grid);card.getStyleClass().add("student-info-record-card");card.setMaxWidth(Double.MAX_VALUE);if(selectable)card.setOnMouseClicked(event->selectExperience(record,card));experienceCardContainer.getChildren().add(card);}}
 private void addCardField(GridPane grid,String key,Object value,int row,int pair){Label k=new Label(key),v=new Label(show(value));k.getStyleClass().add("student-field-key");v.getStyleClass().add("student-field-value");v.setWrapText(true);v.setMaxWidth(Double.MAX_VALUE);grid.add(k,pair*2,row);grid.add(v,pair*2+1,row);ColumnConstraints a=new ColumnConstraints(120),b=new ColumnConstraints();if(grid.getColumnConstraints().isEmpty()){b.setHgrow(Priority.ALWAYS);grid.getColumnConstraints().addAll(a,b,new ColumnConstraints(120),new ColumnConstraints());grid.getColumnConstraints().get(3).setHgrow(Priority.ALWAYS);}}
 private void selectExperience(TeacherWorkExperience record,Pane card){if(selectedExperienceCard!=null)selectedExperienceCard.getStyleClass().remove("student-info-record-card-selected");selectedExperience=record;selectedExperienceCard=card;card.getStyleClass().add("student-info-record-card-selected");editExperienceButton.setDisable(false);deleteExperienceButton.setDisable(false);}
 private void fill(GridPane g,Teacher t,List<String> fields){prepareSixColumns(g);g.getChildren().clear();for(int i=0;i<fields.size();i++){String f=fields.get(i);Label k=new Label(title(f)),v=new Label(show(read(t,f)));k.getStyleClass().add("student-field-key");k.setAlignment(Pos.CENTER_LEFT);k.setMinWidth(136);k.setPrefWidth(136);k.setMaxWidth(136);k.setTooltip(new Tooltip(k.getText()));v.getStyleClass().add("student-field-value");v.setAlignment(Pos.CENTER_LEFT);v.setWrapText(true);v.setMinWidth(0);v.setMaxWidth(Double.MAX_VALUE);v.setTooltip(new Tooltip(v.getText()));int row=i/3,pair=i%3;g.add(k,pair*2,row);g.add(v,pair*2+1,row);}}
 private void beginGlobalEdit(){if(editing||overview==null||overview.getTeacher()==null)return;if(!isAdmin()&&overview.getPendingRequest()!=null){statusLabel.setText("当前修改申请正在审核中，审核完成后才能再次修改");return;}editableControls.clear();editing=true;fillEditable(baseGrid,BASE);fillEditable(jobGrid,JOB);fillEditable(contactGrid,CONTACT);Button cancel=new Button("取消");cancel.getStyleClass().add("btn-secondary");cancel.setOnAction(e->cancelEdit());Button submit=new Button(isAdmin()?"保存修改":"提交修改申请");submit.getStyleClass().add("btn-primary");submit.setOnAction(e->submitEdit());HBox actions=new HBox(8,cancel,submit);actions.setAlignment(Pos.CENTER_RIGHT);contactGrid.add(actions,0,(CONTACT.size()+2)/3,6,1);statusLabel.setText(isAdmin()?"全部信息已进入编辑状态，保存后直接生效":"全部信息已进入编辑状态，提交后等待审核");}
 private void fillEditable(GridPane grid,List<String> fields){prepareSixColumns(grid);grid.getChildren().clear();Teacher teacher=overview.getTeacher();for(int i=0;i<fields.size();i++){String field=fields.get(i);Label key=new Label(title(field));if(Set.of("education","employmentStartDate").contains(field)){Label star=new Label("*");star.setStyle("-fx-text-fill: #dc2626;");key.setGraphic(star);key.setContentDisplay(ContentDisplay.RIGHT);}key.getStyleClass().add("student-field-key");key.setAlignment(Pos.CENTER_LEFT);key.setMinWidth(136);key.setPrefWidth(136);key.setMaxWidth(136);Control value=createEditor(field,showInput(read(teacher,field)));value.setUserData(field);value.setMinWidth(0);value.setMaxWidth(Double.MAX_VALUE);boolean allowed=isAdmin()||EDITABLE.contains(field);value.setDisable(!allowed);if(allowed)editableControls.add(value);int row=i/3,pair=i%3;grid.add(key,pair*2,row);grid.add(value,pair*2+1,row);}}
 private Control createEditor(String field,String initial){Control control;if(Set.of("idIssueDate","birthDate","partyJoinDate","employmentStartDate").contains(field)){DatePicker picker=new DatePicker();if(!initial.isBlank())try{picker.setValue(java.time.LocalDate.parse(initial));}catch(Exception ignored){}control=picker;}else if("education".equals(field)){ComboBox<String> combo=new ComboBox<>(FXCollections.observableArrayList("博士研究生","硕士研究生","本科","专科","其他"));combo.setValue(initial.isBlank()?null:initial);combo.setPromptText("请选择学历");control=combo;}else if("idType".equals(field)){ComboBox<String> combo=new ComboBox<>(FXCollections.observableArrayList("居民身份证","港澳台居民居住证","护照","其他"));combo.setValue(initial);control=combo;}else if("householdType".equals(field)){ComboBox<String> combo=new ComboBox<>(FXCollections.observableArrayList("城镇户口","农村居民户口","集体户口","其他"));combo.setValue(initial);control=combo;}else if(Set.of("partyMember","employed").contains(field)){ComboBox<String> combo=new ComboBox<>(FXCollections.observableArrayList("是","否"));combo.setValue(Set.of("true","1","是","在职").contains(initial)?"是":"否");control=combo;}else control=new TextField(initial);control.getStyleClass().add("form-control");return control;}
 private String controlValue(Control control){if(control instanceof TextInputControl text)return text.getText().trim();if(control instanceof DatePicker date)return date.getValue()==null?"":date.getValue().toString();if(control instanceof ComboBox<?> combo)return combo.getValue()==null?"":String.valueOf(combo.getValue()).trim();return "";}
 private void cancelEdit(){editing=false;editableControls.clear();render();statusLabel.setText("已取消编辑");}
 private void submitEdit(){try{for(Control control:editableControls){if(control instanceof DatePicker picker)picker.commitValue();String field=String.valueOf(control.getUserData());if(Set.of("education","employmentStartDate").contains(field)&&controlValue(control).isBlank()){statusLabel.setText(title(field)+"不能为空");control.requestFocus();return;}}}catch(RuntimeException e){statusLabel.setText("请输入有效日期或使用日历选择");return;}Teacher teacher=overview.getTeacher();Map<String,String> changed=new LinkedHashMap<>();for(Control control:editableControls){String field=String.valueOf(control.getUserData()),old=showInput(read(teacher,field)),now=controlValue(control);if(!old.equals(now))changed.put(field,now);}if(changed.isEmpty()){statusLabel.setText("没有检测到修改内容");return;}if(isAdmin()){Teacher updated=gson.fromJson(gson.toJson(teacher),Teacher.class);try{changed.forEach((field,value)->write(updated,field,value));}catch(Exception exception){statusLabel.setText("格式错误: "+exception.getMessage());return;}service.update(updated,m->Platform.runLater(()->{statusLabel.setText(m.getMessage());if(ok(m)){editing=false;service.query(updated.getTeacherId(),this::receiveOverview);}}));}else submitChanges(teacher,changed);}
 private void prepareSixColumns(GridPane g){g.setAlignment(Pos.CENTER_LEFT);g.setHgap(12);g.setVgap(9);g.setMaxWidth(Double.MAX_VALUE);if(g.getColumnConstraints().size()==6)return;g.getColumnConstraints().clear();for(int i=0;i<6;i++){ColumnConstraints c=new ColumnConstraints();if(i%2==0){c.setMinWidth(136);c.setPrefWidth(136);c.setMaxWidth(136);c.setHgrow(Priority.NEVER);}else{c.setMinWidth(0);c.setPrefWidth(150);c.setMaxWidth(Double.MAX_VALUE);c.setHgrow(Priority.ALWAYS);}c.setFillWidth(true);g.getColumnConstraints().add(c);}}
 private void setupTables(){selectAllTeachers=new CheckBox();selectAllTeachers.setOnAction(e->{if(selectAllTeachers.isSelected())for(Teacher teacher:teacherTable.getItems())selectedTeacherIds.add(teacher.getTeacherId());else for(Teacher teacher:teacherTable.getItems())selectedTeacherIds.remove(teacher.getTeacherId());teacherTable.refresh();updateTeacherSelection();});selectCol.setGraphic(selectAllTeachers);selectCol.setCellFactory(column->new TableCell<>(){private final CheckBox checkBox=new CheckBox();{setAlignment(Pos.CENTER);checkBox.setOnAction(e->{Teacher teacher=getTableView().getItems().get(getIndex());if(checkBox.isSelected())selectedTeacherIds.add(teacher.getTeacherId());else selectedTeacherIds.remove(teacher.getTeacherId());updateTeacherSelection();});}@Override protected void updateItem(Void item,boolean empty){super.updateItem(item,empty);if(empty||getIndex()>=getTableView().getItems().size())setGraphic(null);else{checkBox.setSelected(selectedTeacherIds.contains(getTableView().getItems().get(getIndex()).getTeacherId()));setGraphic(checkBox);}}});idCol.setCellValueFactory(c->s(c.getValue().getTeacherId()));nameCol.setCellValueFactory(c->s(c.getValue().getName()));collegeCol.setCellValueFactory(c->s(c.getValue().getCollege()));departmentCol.setCellValueFactory(c->s(c.getValue().getDepartment()));titleCol.setCellValueFactory(c->s(c.getValue().getTitle()));statusCol.setCellValueFactory(c->s(c.getValue().getEmploymentStatus()));teacherTable.setOnMouseClicked(e->{if(e.getClickCount()==2){Teacher t=teacherTable.getSelectionModel().getSelectedItem();if(t!=null)service.query(t.getTeacherId(),m->Platform.runLater(()->{if(ok(m)){overview=data(m,"overview",TeacherOverviewVO.class);render();tabs.getSelectionModel().select(detailTab);}else statusLabel.setText(m.getMessage());}));}});requestTeacherCol.setCellValueFactory(c->s(c.getValue().getTeacherId()));requestSubmitCol.setCellValueFactory(c->s(c.getValue().getSubmitTime()));requestStatusCol.setCellValueFactory(c->s(reviewStatusText(c.getValue().getStatus())));requestNameCol.setCellValueFactory(c->s(teachers.stream().filter(t->Objects.equals(t.getTeacherId(),c.getValue().getTeacherId())).map(Teacher::getName).findFirst().orElse("-")));requestActionCol.setCellValueFactory(c->new javafx.beans.property.ReadOnlyObjectWrapper<>(c.getValue()));requestActionCol.setCellFactory(col->new TableCell<>(){private final Button button=new Button("查看详情");{button.getStyleClass().add("table-action-button");button.setOnAction(e->{if(getItem()!=null)openReviewDetails(getItem());});}protected void updateItem(TeacherChangeRequest item,boolean empty){super.updateItem(item,empty);setGraphic(empty||item==null?null:button);}});requestReviewCol.setCellValueFactory(c->s(c.getValue().getReviewTime()));requestTable.setOnMouseClicked(e->{if(e.getClickCount()==2)reviewSelected();});}
 private void setupActionColumn(){actionCol.setCellValueFactory(cell->new javafx.beans.property.ReadOnlyObjectWrapper<>(cell.getValue()));actionCol.setCellFactory(column->new TableCell<>(){private final Button button=new Button();{button.getStyleClass().add("table-action-button");button.setOnAction(e->{Teacher teacher=getItem();if(teacher==null||isEmpty())return;service.query(teacher.getTeacherId(),m->Platform.runLater(()->{if(!ok(m)){statusLabel.setText(m.getMessage());return;}overview=data(m,"overview",TeacherOverviewVO.class);render();tabs.getSelectionModel().select(detailTab);}));});}@Override protected void updateItem(Teacher item,boolean empty){super.updateItem(item,empty);button.setText(adminMaintenanceMode?"编辑":"查看详情");setGraphic(empty||item==null?null:button);}});}
 private void setDetailEditable(boolean visible){for(Button button:List.of(editButton,jobEditButton,contactEditButton)){button.setVisible(visible);button.setManaged(visible);}}
 private void loadAdmin(){service.list(m->Platform.runLater(()->{if(ok(m)){List<Teacher> x=data(m,"teachers",new TypeToken<List<Teacher>>(){}.getType());teachers=x==null?new ArrayList<>():new ArrayList<>(x);selectedTeacherIds.clear();teacherTable.setItems(FXCollections.observableArrayList(teachers));updateTeacherSelection();requestTable.refresh();}}));service.reviews(m->Platform.runLater(()->{if(ok(m)){List<TeacherChangeRequest>x=data(m,"requests",new TypeToken<List<TeacherChangeRequest>>(){}.getType());reviewRequests=x==null?new ArrayList<>():new ArrayList<>(x);applyReviewBucket();}}));}
 private void updateTeacherSelection(){if(selectAllTeachers!=null){long count=teacherTable.getItems().stream().filter(t->selectedTeacherIds.contains(t.getTeacherId())).count();selectAllTeachers.setIndeterminate(count>0&&count<teacherTable.getItems().size());selectAllTeachers.setSelected(!teacherTable.getItems().isEmpty()&&count==teacherTable.getItems().size());}if(selectedTeacherCountLabel!=null)selectedTeacherCountLabel.setText("已选择 "+selectedTeacherIds.size()+" 人");if(exportTeachersButton!=null)exportTeachersButton.setDisable(selectedTeacherIds.isEmpty());}
 @FXML private void exportSelectedTeachers(){List<Teacher> selected=teachers.stream().filter(t->selectedTeacherIds.contains(t.getTeacherId())).toList();if(selected.isEmpty()){AlertUtil.showWarning("请选择教师","请先勾选需要导出的教师。");return;}FileChooser chooser=new FileChooser();chooser.setTitle("导出教师信息");chooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("Excel 工作簿 (*.xlsx)","*.xlsx"));chooser.setInitialFileName("教师信息_"+java.time.LocalDate.now()+".xlsx");File chosen=chooser.showSaveDialog(teacherTable.getScene().getWindow());if(chosen==null)return;File output=chosen.getName().toLowerCase(Locale.ROOT).endsWith(".xlsx")?chosen:new File(chosen.getParentFile(),chosen.getName()+".xlsx");exportTeachersButton.setDisable(true);statusLabel.setText("正在导出 "+selected.size()+" 名教师的信息...");Task<Void> task=new Task<>(){@Override protected Void call()throws Exception{TeacherExcelExport.export(selected,output);return null;}};task.setOnSucceeded(e->{exportTeachersButton.setDisable(false);statusLabel.setText("已导出 "+selected.size()+" 名教师的信息");AlertUtil.showInfo("导出成功","Excel 已保存至：\n"+output.getAbsolutePath());});task.setOnFailed(e->{exportTeachersButton.setDisable(false);statusLabel.setText("教师信息导出失败");Throwable error=task.getException();AlertUtil.showError("导出失败",error==null?"无法生成 Excel 文件。":"无法生成 Excel 文件：\n"+error.getMessage());});Thread worker=new Thread(task,"teacher-excel-export");worker.setDaemon(true);worker.start();}
 @FXML private void reviewSelected(){TeacherChangeRequest r=requestTable.getSelectionModel().getSelectedItem();if(r!=null)openReviewDetails(r);}
 private void closeReviewDetails(){reviewLoadGeneration++;if(reviewDetailTab!=null){tabs.getTabs().remove(reviewDetailTab);reviewDetailTab=null;}tabs.getSelectionModel().select(reviewTab);}
 private void openReviewDetails(TeacherChangeRequest row){
  closeReviewDetails();long generation=++reviewLoadGeneration;
  VBox page=new VBox(14);page.getStyleClass().add("student-page");page.setPadding(new javafx.geometry.Insets(18,24,20,24));
  Button back=new Button("← 返回审核总览");back.getStyleClass().add("btn-secondary");back.setOnAction(e->closeReviewDetails());Label heading=new Label("申请修改详情");heading.getStyleClass().add("student-section-title");page.getChildren().addAll(new HBox(14,back,heading),new Label("正在加载完整信息…"));
  reviewDetailTab=new Tab("审核详情",page);tabs.getTabs().add(reviewDetailTab);tabs.getSelectionModel().select(reviewDetailTab);
  service.reviewQuery(row.getRequestId(),message->Platform.runLater(()->{if(generation!=reviewLoadGeneration)return;if(!ok(message)){showReviewLoadError(page,message.getMessage(),row);return;}TeacherChangeRequest request=data(message,"request",TeacherChangeRequest.class);if(request==null){showReviewLoadError(page,"审核申请不存在",row);return;}
   service.query(request.getTeacherId(),response->Platform.runLater(()->{if(generation!=reviewLoadGeneration)return;if(!ok(response)){showReviewLoadError(page,response.getMessage(),row);return;}TeacherOverviewVO profile=data(response,"overview",TeacherOverviewVO.class);if(profile==null||profile.getTeacher()==null){showReviewLoadError(page,"教师档案不存在",row);return;}renderReviewDetail(page,request,profile,generation);}));
  }));
 }
 private void showReviewLoadError(VBox page,String message,TeacherChangeRequest row){statusLabel.setText(message);Label error=new Label("加载失败："+message);error.setWrapText(true);Button retry=new Button("重新加载");retry.getStyleClass().add("btn-secondary");retry.setOnAction(e->openReviewDetails(row));page.getChildren().set(1,new VBox(12,error,retry));}
 private VBox reviewSection(String title){VBox section=new VBox(10);section.getStyleClass().add("student-panel");Label label=new Label(title);label.getStyleClass().add("student-section-title");section.getChildren().add(label);return section;}
 private void renderReviewDetail(VBox page,TeacherChangeRequest request,TeacherOverviewVO profile,long generation){
  VBox records=new VBox(14);records.setMinWidth(850);HBox.setHgrow(records,Priority.ALWAYS);
  Map<String,TeacherChangeItem> changes=new HashMap<>();for(TeacherChangeItem item:request.getItems())changes.put(item.getFieldName(),item);
  List<List<String>> groups=List.of(BASE,JOB,CONTACT);String[] names={"个人基本信息","任职信息","联系信息"};
  for(int k=0;k<groups.size();k++){VBox section=reviewSection(names[k]);GridPane grid=new GridPane();grid.setHgap(12);grid.setVgap(9);prepareSixColumns(grid);List<String> fields=groups.get(k);for(int i=0;i<fields.size();i++){String field=fields.get(i);Label key=new Label(title(field));key.getStyleClass().add("student-field-key");key.setMaxWidth(Double.MAX_VALUE);javafx.scene.Node value;TeacherChangeItem change=changes.get(field);if(change==null){Label label=new Label(show(read(profile.getTeacher(),field)));label.setWrapText(true);value=label;}else{Label old=new Label("原值："+reviewFieldValue(field,change.getOldValue())),updated=new Label("申请值："+reviewFieldValue(field,change.getNewValue()));old.setWrapText(true);updated.setWrapText(true);updated.setStyle("-fx-font-weight: bold;");VBox diff=new VBox(4,old,updated);diff.setStyle("-fx-background-color: #fff5d6; -fx-padding: 8; -fx-background-radius: 5;");value=diff;}grid.add(key,(i%3)*2,i/3);grid.add(value,(i%3)*2+1,i/3);}section.getChildren().add(grid);records.getChildren().add(section);}
  VBox work=reviewSection("工作经历"),workCards=new VBox(10),family=reviewSection("主要社会关系"),familyCards=new VBox(10);renderExperiences(profile.getWorkExperiences(),workCards,false);renderFamilyMembers(profile.getFamilyMembers(),familyCards,false);work.getChildren().add(workCards);family.getChildren().add(familyCards);records.getChildren().addAll(work,family);
  VBox actions=reviewSection("审核处理");actions.setMinWidth(250);actions.setPrefWidth(280);TextArea reason=new TextArea(request.getReviewRemark());reason.setPromptText("填写审核理由");reason.setWrapText(true);reason.setPrefRowCount(6);boolean pending=request.getStatus()==StudentChangeStatus.PENDING;reason.setEditable(pending);Button approve=new Button("通过"),reject=new Button("不通过");approve.getStyleClass().add("btn-primary");reject.getStyleClass().add("btn-secondary");approve.setDisable(!pending);reject.setDisable(!pending);
  actions.getChildren().addAll(new Label("状态："+reviewStatusText(request.getStatus())),new Label("提交时间："+show(request.getSubmitTime())),new Label("处理时间："+show(request.getReviewTime())),new HBox(8,approve,reject),new Label("理由"),reason);
  java.util.function.Consumer<StudentChangeStatus> decide=result->{if(generation!=reviewLoadGeneration)return;approve.setDisable(true);reject.setDisable(true);TeacherReviewVO value=new TeacherReviewVO();value.setRequestId(request.getRequestId());value.setReviewResult(result);value.setReviewRemark(reason.getText()==null?"":reason.getText().trim());service.review(value,message->Platform.runLater(()->{if(generation!=reviewLoadGeneration)return;statusLabel.setText(message.getMessage());if(ok(message)){closeReviewDetails();showCompletedReviews=true;teacherReviewSearchIdField.clear();teacherReviewSearchStatusField.clear();loadAdmin();}else{approve.setDisable(false);reject.setDisable(false);}}));};approve.setOnAction(e->decide.accept(StudentChangeStatus.APPROVED));reject.setOnAction(e->decide.accept(StudentChangeStatus.REJECTED));
  HBox body=new HBox(18,records,actions);body.setAlignment(Pos.TOP_LEFT);ScrollPane scroll=new ScrollPane(body);scroll.setFitToWidth(true);scroll.getStyleClass().add("student-scroll");VBox.setVgrow(scroll,Priority.ALWAYS);page.getChildren().set(1,scroll);
 }
 private String reviewFieldValue(String field,String value){if(value==null||value.isBlank())return "-";if(Set.of("partyMember","employed").contains(field))return Set.of("true","1","是").contains(value)?"是":"否";return value;}

 @FXML private void addWorkExperience(){showWorkExperienceEditor(null);}
 @FXML private void editWorkExperience(){if(selectedExperience==null){statusLabel.setText("请先选择工作经历");return;}showWorkExperienceEditor(selectedExperience);}
 @FXML private void deleteWorkExperience(){if(selectedExperience==null){statusLabel.setText("请先选择工作经历");return;}Alert alert=new Alert(Alert.AlertType.CONFIRMATION,"确定删除选中的工作经历吗？",ButtonType.OK,ButtonType.CANCEL);alert.setHeaderText(null);if(alert.showAndWait().orElse(ButtonType.CANCEL)!=ButtonType.OK)return;service.deleteWorkExperience(selectedExperience.getExperienceId(),m->Platform.runLater(()->{statusLabel.setText(m.getMessage());if(ok(m))service.overview(this::receiveOverview);}));}
 private void showWorkExperienceEditor(TeacherWorkExperience source){Dialog<ButtonType> dialog=new Dialog<>();dialog.setTitle(source==null?"新增工作经历":"编辑工作经历");GridPane grid=new GridPane();grid.setHgap(12);grid.setVgap(10);grid.setPadding(new javafx.geometry.Insets(8,12,8,12));DatePicker start=new DatePicker(),end=new DatePicker();TextField organization=new TextField(),department=new TextField(),position=new TextField(),description=new TextField();if(source!=null){if(source.getStartDate()!=null)start.setValue(source.getStartDate().toLocalDate());if(source.getEndDate()!=null)end.setValue(source.getEndDate().toLocalDate());organization.setText(input(source.getOrganization()));department.setText(input(source.getDepartment()));position.setText(input(source.getPosition()));description.setText(input(source.getDescription()));}start.setPromptText("必填");end.setPromptText("留空表示至今");Control[] controls={start,end,organization,department,position,description};String[] labels={"开始时间","结束时间","工作单位","所在部门","职务","工作内容"};for(int i=0;i<labels.length;i++){controls[i].setPrefWidth(360);Label fieldLabel=new Label(labels[i]);if(i==0||i==2||i==3||i==4){Label star=new Label("*");star.setStyle("-fx-text-fill: #dc2626; -fx-font-weight: bold;");fieldLabel.setGraphic(star);fieldLabel.setContentDisplay(ContentDisplay.RIGHT);}grid.add(fieldLabel,0,i);grid.add(controls[i],1,i);}dialog.getDialogPane().setContent(grid);dialog.getDialogPane().getButtonTypes().addAll(ButtonType.OK,ButtonType.CANCEL);dialog.showAndWait().ifPresent(button->{if(button!=ButtonType.OK)return;try{if(start.getValue()==null)throw new IllegalArgumentException("开始时间不能为空");if(organization.getText().isBlank())throw new IllegalArgumentException("工作单位不能为空");if(department.getText().isBlank())throw new IllegalArgumentException("所在部门不能为空");if(position.getText().isBlank())throw new IllegalArgumentException("职务不能为空");if(end.getValue()!=null&&end.getValue().isBefore(start.getValue()))throw new IllegalArgumentException("结束时间不能早于开始时间");TeacherWorkExperience value=source==null?new TeacherWorkExperience():gson.fromJson(gson.toJson(source),TeacherWorkExperience.class);value.setStartDate(Date.valueOf(start.getValue()));value.setEndDate(end.getValue()==null?null:Date.valueOf(end.getValue()));value.setOrganization(organization.getText().trim());value.setDepartment(department.getText().trim());value.setPosition(position.getText().trim());value.setDescription(description.getText().trim());java.util.function.Consumer<Message> done=m->Platform.runLater(()->{statusLabel.setText(m.getMessage());if(ok(m))service.overview(this::receiveOverview);});if(source==null)service.addWorkExperience(value,done);else service.updateWorkExperience(value,done);}catch(Exception exception){statusLabel.setText("工作经历格式错误: "+exception.getMessage());}});}
 private String month(Date value){return value==null?"":value.toString().substring(0,7);}private String input(Object value){return value==null?"":String.valueOf(value);}
 private void submitChanges(Teacher t,Map<String,String> changed){TeacherChangeRequest request=new TeacherChangeRequest();List<TeacherChangeItem> items=new ArrayList<>();changed.forEach((field,value)->{TeacherChangeItem item=new TeacherChangeItem();item.setFieldName(field);item.setOldValue(showInput(read(t,field)));item.setNewValue(value);items.add(item);});request.setItems(items);service.submit(request,m->Platform.runLater(()->{statusLabel.setText(m.getMessage());if(ok(m)){editing=false;service.overview(this::receiveOverview);}}));}
 private boolean isAdmin(){String r=ClientSession.getInstance().getRole();return "ADMIN".equalsIgnoreCase(r)||"管理员".equals(r);} private boolean ok(Message m){return m!=null&&m.getCode()==MessageCode.SUCCESS;} private<T>T data(Message m,String k,Type t){return gson.fromJson(gson.toJson(m.getData().get(k)),t);} private SimpleStringProperty s(Object v){return new SimpleStringProperty(show(v));}
 private Object read(Teacher t,String f){try{String x=Character.toUpperCase(f.charAt(0))+f.substring(1);try{return Teacher.class.getMethod("get"+x).invoke(t);}catch(NoSuchMethodException e){return Teacher.class.getMethod("is"+x).invoke(t);}}catch(Exception e){return null;}}
 private void write(Teacher t,String f,String v){try{Field field=Teacher.class.getDeclaredField(f);String x=Character.toUpperCase(f.charAt(0))+f.substring(1);Method m=Arrays.stream(Teacher.class.getMethods()).filter(z->z.getName().equals("set"+x)).findFirst().orElseThrow();Object q=field.getType()==boolean.class?Set.of("是","true","1","在职").contains(v):field.getType()==Date.class?(v.isBlank()?null:Date.valueOf(v)):v.trim();m.invoke(t,q);}catch(Exception e){throw new IllegalArgumentException(f);}}
 private List<String> concat(List<String>...xs){List<String>o=new ArrayList<>();for(List<String>x:xs)o.addAll(x);return o;} private String show(Object v){if(v==null||String.valueOf(v).isBlank())return "-";return v instanceof Boolean?((Boolean)v?"是":"否"):String.valueOf(v);}private String showInput(Object v){if(v==null)return "";return v instanceof Boolean?((Boolean)v?"是":"否"):String.valueOf(v);}
 private String title(String f){return Map.ofEntries(Map.entry("UID","用户名"),Map.entry("teacherId","工号"),Map.entry("name","姓名"),Map.entry("politicalStatus","政治面貌"),Map.entry("nationality","民族"),Map.entry("gender","性别"),Map.entry("idType","身份证件类型"),Map.entry("idNumber","身份证号"),Map.entry("idIssueDate","身份证签发日期"),Map.entry("birthDate","出生日期"),Map.entry("nativePlace","籍贯"),Map.entry("householdType","户口性质"),Map.entry("birthPlace","出生地"),Map.entry("sourcePlace","生源地"),Map.entry("registeredResidence","户口所在地"),Map.entry("partyMember","是否党员"),Map.entry("partyJoinDate","入党时间"),Map.entry("healthStatus","健康状况"),Map.entry("employed","是否在职"),Map.entry("employmentStatus","任职状态"),Map.entry("campus","校区"),Map.entry("college","学院"),Map.entry("department","部门"),Map.entry("title","职称"),Map.entry("education","学历"),Map.entry("employmentStartDate","入职日期"),Map.entry("position","职务"),Map.entry("telephone","联系电话"),Map.entry("mobile","手机号"),Map.entry("email","电子邮箱"),Map.entry("qq","QQ号"),Map.entry("wechat","微信号"),Map.entry("officeAddress","在校办公地址"),Map.entry("emergencyContact","紧急联系人"),Map.entry("emergencyPhone","紧急联系人联系方式")).getOrDefault(f,f);}
 private void renderFamilyMembers(List<TeacherFamilyMember> records){renderFamilyMembers(records,familyCardContainer,true);}
 private void renderFamilyMembers(List<TeacherFamilyMember> records,VBox familyCardContainer,boolean selectable){
  selectedFamilyMember=null;selectedFamilyCard=null;
  editFamilyButton.setDisable(true);deleteFamilyButton.setDisable(true);familyCardContainer.getChildren().clear();
  if(records==null||records.isEmpty()){
   Label empty=new Label("暂无家庭成员");empty.getStyleClass().add("student-info-empty-card");empty.setMaxWidth(Double.MAX_VALUE);familyCardContainer.getChildren().add(empty);return;
  }
  for(TeacherFamilyMember record:records){
   GridPane grid=new GridPane();grid.getStyleClass().add("student-info-record-grid");grid.setMaxWidth(Double.MAX_VALUE);
   addCardField(grid,"姓名",record.getName(),0,0);addCardField(grid,"与本人关系",record.getRelationship(),0,1);
   addCardField(grid,"出生年月",record.getBirthDate(),1,0);addCardField(grid,"健康状况",record.getHealthStatus(),1,1);
   addCardField(grid,"户口所在地",record.getRegisteredResidence(),2,0);addCardField(grid,"联系电话",record.getPhone(),2,1);
   addCardField(grid,"工作单位",record.getWorkplace(),3,0);addCardField(grid,"工作单位地址",record.getWorkplaceAddress(),3,1);
   VBox card=new VBox(grid);card.getStyleClass().add("student-info-record-card");card.setMaxWidth(Double.MAX_VALUE);
   if(selectable)card.setOnMouseClicked(event->{
    if(selectedFamilyCard!=null)selectedFamilyCard.getStyleClass().remove("student-info-record-card-selected");
    selectedFamilyMember=record;selectedFamilyCard=card;card.getStyleClass().add("student-info-record-card-selected");
    editFamilyButton.setDisable(false);deleteFamilyButton.setDisable(false);
   });
   familyCardContainer.getChildren().add(card);
  }
 }
 @FXML private void addFamilyMember(){showFamilyMemberEditor(null);}
 @FXML private void editFamilyMember(){if(selectedFamilyMember!=null)showFamilyMemberEditor(selectedFamilyMember);}
 @FXML private void deleteFamilyMember(){
  if(selectedFamilyMember==null)return;
  TeacherFamilyMember member=selectedFamilyMember;
  Alert alert=new Alert(Alert.AlertType.CONFIRMATION,"确定删除选中的家庭成员吗？",ButtonType.OK,ButtonType.CANCEL);alert.setHeaderText(null);
  if(alert.showAndWait().orElse(ButtonType.CANCEL)==ButtonType.OK)service.deleteFamilyMember(member.getMemberId(),this::familyMemberSaved);
 }
 private void familyMemberSaved(Message message){Platform.runLater(()->{statusLabel.setText(message.getMessage());if(ok(message))service.overview(this::receiveOverview);});}
 private void showFamilyMemberEditor(TeacherFamilyMember source){
  Dialog<ButtonType> dialog=new Dialog<>();dialog.setTitle(source==null?"新增家庭主要关系成员":"编辑家庭主要关系成员");dialog.setHeaderText("请在同一表单中填写全部信息");
  GridPane grid=new GridPane();grid.setHgap(12);grid.setVgap(10);grid.setPadding(new javafx.geometry.Insets(8,12,8,12));
  String[] names={"姓名","与本人关系","出生年月","户口所在地","工作单位","工作单位地址","健康状况","联系电话"};
  String[] initial=source==null?new String[8]:new String[]{source.getName(),source.getRelationship(),source.getBirthDate()==null?null:source.getBirthDate().toString(),source.getRegisteredResidence(),source.getWorkplace(),source.getWorkplaceAddress(),source.getHealthStatus(),source.getPhone()};
  Set<Integer> required=Set.of(0,1,3,4,7);
  List<java.util.function.Supplier<String>> readers=new ArrayList<>();
  for(int i=0;i<names.length;i++){
   Control control;String value=initial[i]==null?"":initial[i];
   if(i==1){
    ComboBox<String> relationship=new ComboBox<>(FXCollections.observableArrayList("父亲","母亲","配偶","子女","兄弟","姐妹","祖父","祖母","外祖父","外祖母","其他"));
    relationship.setValue(value.isBlank()?null:value);control=relationship;readers.add(()->relationship.getValue()==null?"":relationship.getValue());
   }else if(i==2){
    DatePicker birth=new DatePicker();if(!value.isBlank())birth.setValue(java.time.LocalDate.parse(value));control=birth;
    readers.add(()->{birth.commitValue();return birth.getValue()==null?"":birth.getValue().toString();});
   }else{TextField text=new TextField(value);control=text;readers.add(()->text.getText().trim());}
   control.setPrefWidth(360);Label label=new Label(names[i]);
   if(required.contains(i)){Label star=new Label("*");star.setStyle("-fx-text-fill: #dc2626; -fx-font-weight: bold;");label.setGraphic(star);label.setContentDisplay(ContentDisplay.RIGHT);}
   grid.add(label,0,i);grid.add(control,1,i);
  }
  Label error=new Label();error.setStyle("-fx-text-fill: #dc2626;");error.setWrapText(true);grid.add(error,0,names.length,2,1);
  dialog.getDialogPane().setContent(grid);dialog.getDialogPane().getButtonTypes().addAll(ButtonType.OK,ButtonType.CANCEL);
  Button save=(Button)dialog.getDialogPane().lookupButton(ButtonType.OK);
  Button cancel=(Button)dialog.getDialogPane().lookupButton(ButtonType.CANCEL);
  boolean[] saving={false};
  dialog.setOnCloseRequest(event->{if(saving[0])event.consume();});
  save.addEventFilter(javafx.event.ActionEvent.ACTION,event->{
   event.consume();
   if(saving[0])return;
   try{
    String[] values=new String[names.length];
    for(int i=0;i<names.length;i++){values[i]=readers.get(i).get();if(required.contains(i)&&values[i].isBlank())throw new IllegalArgumentException(names[i]+"不能为空");}
    TeacherFamilyMember member=source==null?new TeacherFamilyMember():gson.fromJson(gson.toJson(source),TeacherFamilyMember.class);
    member.setName(values[0]);member.setRelationship(values[1]);member.setBirthDate(values[2].isBlank()?null:Date.valueOf(values[2]));
    member.setRegisteredResidence(values[3]);member.setWorkplace(values[4]);member.setWorkplaceAddress(values[5]);member.setHealthStatus(values[6]);member.setPhone(values[7]);
    saving[0]=true;save.setDisable(true);cancel.setDisable(true);error.setText("正在保存，请稍候...");
    java.util.function.Consumer<Message> done=message->Platform.runLater(()->{
     saving[0]=false;save.setDisable(false);cancel.setDisable(false);
     if(ok(message)){
      dialog.setResult(ButtonType.OK);dialog.close();familyMemberSaved(message);
     }else{
      String reason=message==null||message.getMessage()==null?"未收到保存结果，请刷新列表确认后再重试。":message.getMessage();
      if(reason.contains("版本不一致"))reason="保存未成功：服务端版本过旧。请重新编译并重启服务端，然后在此重试；填写内容已保留。";
      error.setText(reason);statusLabel.setText(reason);
     }
    });
    if(source==null)service.addFamilyMember(member,done);else service.updateFamilyMember(member,done);
   }catch(Exception exception){
    saving[0]=false;save.setDisable(false);cancel.setDisable(false);
    error.setText(exception.getMessage()==null?"请检查填写内容":exception.getMessage());
   }
  });
  dialog.showAndWait();
 } @FXML private void exportTeacherPdf(){
  if(overview==null||overview.getTeacher()==null){AlertUtil.showWarning("暂时无法导出","教师信息尚未加载完成，请稍后重试。");return;}
  Teacher teacher=gson.fromJson(gson.toJson(overview.getTeacher()),Teacher.class);
  List<TeacherWorkExperience> experiences=overview.getWorkExperiences()==null?List.of():List.copyOf(overview.getWorkExperiences());
  List<TeacherFamilyMember> family=overview.getFamilyMembers()==null?List.of():List.copyOf(overview.getFamilyMembers());
  FileChooser chooser=new FileChooser();chooser.setTitle("导出教师信息");chooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("PDF 文件 (*.pdf)","*.pdf"));
  String name=(input(teacher.getTeacherId())+"_"+input(teacher.getName())+"_教师信息").replaceAll("[\\\\/:*?\"<>|]","_");
  chooser.setInitialFileName(name+".pdf");File downloads=new File(System.getProperty("user.home"),"Downloads");if(downloads.isDirectory())chooser.setInitialDirectory(downloads);
  File selected=chooser.showSaveDialog(tabs.getScene().getWindow());if(selected==null)return;
  File output=selected.getName().toLowerCase(Locale.ROOT).endsWith(".pdf")?selected:new File(selected.getParentFile(),selected.getName()+".pdf");
  exportPdfButton.setDisable(true);statusLabel.setText("正在导出教师信息...");
  Task<Void> task=new Task<>(){@Override protected Void call()throws Exception{util.pdf.TeacherPdfExport.export(teacher,experiences,family,output);return null;}};
  task.setOnSucceeded(event->{exportPdfButton.setDisable(false);statusLabel.setText("教师信息已导出");AlertUtil.showInfo("导出成功","PDF 已保存至：\n"+output.getAbsolutePath());});
  task.setOnFailed(event->{exportPdfButton.setDisable(false);statusLabel.setText("教师信息导出失败");AlertUtil.showError("导出失败",task.getException()==null?"无法生成 PDF 文件。":task.getException().getMessage());});
  Thread worker=new Thread(task,"teacher-pdf-export");worker.setDaemon(true);worker.start();
 }}




