package service;
import java.util.function.Consumer; import network.SocketClient; import entity.*; import protocol.*; import vo.StudentReviewVO;
public class StudentClientService implements IStudentClientService {
 private final SocketClient socket; public StudentClientService(SocketClient s){socket=s;}
 private void send(String action,String key,Object value,Consumer<Message> c){Message m=new Message(MessageType.REQUEST,"student",action);if(key!=null)m.putData(key,value);socket.sendAsync(m).whenComplete((r,e)->{if(e==null)c.accept(r);else{Message f=new Message(MessageType.RESPONSE,"student",action);f.setCode(MessageCode.ERROR);f.setMessage("连接学籍服务失败: "+e.getMessage());c.accept(f);}});}
 public void queryOverview(Consumer<Message> c){send("queryOverview",null,null,c);} public void submitChangeRequest(StudentChangeRequest r,Consumer<Message> c){send("submitChangeRequest","request",r,c);} public void queryMyRequests(Consumer<Message> c){send("queryMyRequests",null,null,c);} public void cancelChangeRequest(long id,Consumer<Message> c){send("cancelChangeRequest","requestId",id,c);}
 public void listStudents(Consumer<Message> c){send("listStudents",null,null,c);} public void queryStudentOverview(String id,Consumer<Message> c){send("queryStudentOverview","studentId",id,c);} public void listPendingRequests(Consumer<Message> c){send("listPendingRequests",null,null,c);} public void queryChangeRequest(long id,Consumer<Message> c){send("queryChangeRequest","requestId",id,c);} public void reviewChangeRequest(StudentReviewVO r,Consumer<Message> c){send("reviewChangeRequest","review",r,c);}
 public void updateStudentByAdmin(Student s,Consumer<Message> c){send("updateStudentByAdmin","student",s,c);} public void addAward(StudentAward a,Consumer<Message> c){send("addAward","award",a,c);} public void updateAward(StudentAward a,Consumer<Message> c){send("updateAward","award",a,c);} public void deleteAward(long id,Consumer<Message> c){send("deleteAward","awardId",id,c);} public void addAid(StudentAid a,Consumer<Message> c){send("addAid","aid",a,c);} public void updateAid(StudentAid a,Consumer<Message> c){send("updateAid","aid",a,c);} public void deleteAid(long id,Consumer<Message> c){send("deleteAid","aidId",id,c);}
}
