package dao;
import entity.StudentExperience; import util.DBUtil; import java.sql.*; import java.util.*;
public class StudentExperienceDAO {
 public List<StudentExperience> findByStudentId(String id)throws SQLException{List<StudentExperience>o=new ArrayList<>();try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM tblStudentExperience WHERE studentId=? ORDER BY startDate")){p.setString(1,id);try(ResultSet r=p.executeQuery()){while(r.next()){StudentExperience x=new StudentExperience();x.setExperienceId(r.getLong("experienceId"));x.setStudentId(id);x.setStartDate(r.getDate("startDate"));x.setEndDate(r.getDate("endDate"));x.setSchoolName(r.getString("schoolName"));x.setEducationLevel(r.getString("educationLevel"));x.setDescription(r.getString("description"));o.add(x);}}}return o;}
 public StudentExperience findById(String studentId,long id)throws SQLException{for(StudentExperience x:findByStudentId(studentId))if(x.getExperienceId()==id)return x;return null;}
 public boolean insert(StudentExperience x)throws SQLException{try(Connection c=DBUtil.getConnection()){return insert(c,x);}}
 public boolean insert(Connection c,StudentExperience x)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO tblStudentExperience(studentId,startDate,endDate,schoolName,educationLevel,description)VALUES(?,?,?,?,?,?)")){p.setString(1,x.getStudentId());p.setDate(2,x.getStartDate());p.setDate(3,x.getEndDate());p.setString(4,x.getSchoolName());p.setString(5,x.getEducationLevel());p.setString(6,x.getDescription());return p.executeUpdate()==1;}}
 public boolean update(String studentId,StudentExperience x)throws SQLException{try(Connection c=DBUtil.getConnection()){return update(c,studentId,x);}}
 public boolean update(Connection c,String studentId,StudentExperience x)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE tblStudentExperience SET startDate=?,endDate=?,schoolName=?,educationLevel=?,description=? WHERE experienceId=? AND studentId=?")){p.setDate(1,x.getStartDate());p.setDate(2,x.getEndDate());p.setString(3,x.getSchoolName());p.setString(4,x.getEducationLevel());p.setString(5,x.getDescription());p.setLong(6,x.getExperienceId());p.setString(7,studentId);return p.executeUpdate()==1;}}
 public boolean delete(String studentId,long id)throws SQLException{try(Connection c=DBUtil.getConnection()){return delete(c,studentId,id);}}
 public boolean delete(Connection c,String studentId,long id)throws SQLException{try(PreparedStatement p=c.prepareStatement("DELETE FROM tblStudentExperience WHERE experienceId=? AND studentId=?")){p.setLong(1,id);p.setString(2,studentId);return p.executeUpdate()==1;}}
}
