package dao;
import entity.*; import util.DBUtil; import java.lang.reflect.*; import java.sql.*; import java.util.*;
public class StudentDAO {
 private static final List<String>C=List.of("studentId","userId","name","gender","politicalStatus","nationality","idType","idNumber","idIssueDate","birthDate","nativePlace","householdType","birthPlace","sourcePlace","registeredResidence","leagueMember","leagueJoinDate","partyMember","partyJoinDate","healthStatus","studentCategory","registered","inSchool","studentStatus","campus","grade","college","major","className","educationLevel","trainingMode","schoolingLength","counselorName","counselorPhone","candidateCategory","admissionDate","admissionMethod","graduationSchool","middleSchoolClass","middleSchoolTeacher","telephone","mobile","email","qq","wechat","campusAddress","emergencyContact","emergencyPhone");
 public Student findByUserId(String v)throws SQLException{return one("userId",v);} public Student findByStudentId(String v)throws SQLException{return one("studentId",v);}
 private Student one(String k,String v)throws SQLException{try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM tblStudent WHERE "+k+"=?")){p.setString(1,v);try(ResultSet r=p.executeQuery()){return r.next()?map(r):null;}}}
 public List<Student> findAll()throws SQLException{List<Student>o=new ArrayList<>();try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM tblStudent ORDER BY studentId");ResultSet r=p.executeQuery()){while(r.next())o.add(map(r));}return o;}
 public boolean update(Student s)throws SQLException{List<String>f=C.subList(1,C.size());String set=String.join(",",f.stream().map(x->x+"=?").toList());try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("UPDATE tblStudent SET "+set+" WHERE studentId=?")){bind(p,s,f);p.setString(f.size()+1,s.getStudentId());return p.executeUpdate()==1;}}
 public boolean updateApprovedFields(Connection c,String id,List<StudentChangeItem>items)throws SQLException{Set<String>a=new HashSet<>(C);a.remove("studentId");a.remove("userId");if(items==null||items.isEmpty())return false;Set<String>seen=new HashSet<>();for(StudentChangeItem i:items)if(i.getFieldName()==null||!a.contains(i.getFieldName())||!seen.add(i.getFieldName()))throw new SQLException("修改字段无效");String set=String.join(",",items.stream().map(i->i.getFieldName()+"=?").toList());try(PreparedStatement p=c.prepareStatement("UPDATE tblStudent SET "+set+" WHERE studentId=?")){int n=1;for(StudentChangeItem i:items)p.setString(n++,i.getNewValue());p.setString(n,id);return p.executeUpdate()==1;}}
 private static void bind(PreparedStatement p,Student s,List<String>fs)throws SQLException{try{int n=1;for(String x:fs){Field f=Student.class.getDeclaredField(x);f.setAccessible(true);p.setObject(n++,f.get(s));}}catch(ReflectiveOperationException e){throw new SQLException(e);}}
 private static Student map(ResultSet r)throws SQLException{Student s=new Student();try{for(String x:C){Field f=Student.class.getDeclaredField(x);f.setAccessible(true);if(f.getType()==boolean.class)f.setBoolean(s,r.getBoolean(x));else if(f.getType()==int.class)f.setInt(s,r.getInt(x));else if(f.getType()==java.sql.Date.class)f.set(s,r.getDate(x));else f.set(s,r.getString(x));}return s;}catch(ReflectiveOperationException e){throw new SQLException(e);}}
}
