package dao;
import entity.*; import enums.StudentChangeStatus; import util.DBUtil; import java.sql.*; import java.util.*;
@SuppressWarnings({"SqlNoDataSourceInspection", "SqlResolve"})
public class StudentChangeRequestDAO {
 private final StudentChangeItemDAO items=new StudentChangeItemDAO();
 public long insert(Connection c,StudentChangeRequest r)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO tblStudentChangeRequest(studentId,status,submitTime)VALUES(?,'PENDING',CURRENT_TIMESTAMP)",Statement.RETURN_GENERATED_KEYS)){p.setString(1,r.getStudentId());p.executeUpdate();try(ResultSet k=p.getGeneratedKeys()){if(!k.next())throw new SQLException("未生成申请编号");long id=k.getLong(1);items.insertAll(c,id,r.getItems());return id;}}}
 public StudentChangeRequest findById(long id)throws SQLException{try(Connection c=DBUtil.getConnection()){return findById(c,id);}} public StudentChangeRequest findById(Connection c,long id)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT * FROM tblStudentChangeRequest WHERE requestId=?")){p.setLong(1,id);try(ResultSet r=p.executeQuery()){if(!r.next())return null;StudentChangeRequest x=map(r);x.setItems(items.findByRequestId(c,id));return x;}}}
 public List<StudentChangeRequest> findByStudentId(String id)throws SQLException{return list("SELECT * FROM tblStudentChangeRequest WHERE studentId=? ORDER BY submitTime DESC",id);} public List<StudentChangeRequest> findPending()throws SQLException{return list("SELECT * FROM tblStudentChangeRequest WHERE status='PENDING' ORDER BY submitTime",null);} public StudentChangeRequest findPendingByStudentId(String id)throws SQLException{try(Connection c=DBUtil.getConnection()){return findPendingByStudentId(c,id);}} public StudentChangeRequest findPendingByStudentId(Connection c,String id)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT * FROM tblStudentChangeRequest WHERE studentId=? AND status='PENDING' ORDER BY submitTime DESC LIMIT 1")){p.setString(1,id);try(ResultSet r=p.executeQuery()){if(!r.next())return null;StudentChangeRequest x=map(r);x.setItems(items.findByRequestId(c,x.getRequestId()));return x;}}}
 private List<StudentChangeRequest> list(String q,String a)throws SQLException{List<StudentChangeRequest>o=new ArrayList<>();try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement(q)){if(a!=null)p.setString(1,a);try(ResultSet r=p.executeQuery()){while(r.next()){StudentChangeRequest x=map(r);x.setItems(items.findByRequestId(c,x.getRequestId()));o.add(x);}}}return o;}
 public boolean review(Connection c,long id,StudentChangeStatus s,String who,String note)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE tblStudentChangeRequest SET status=?,reviewerId=?,reviewTime=CURRENT_TIMESTAMP,reviewRemark=? WHERE requestId=? AND status='PENDING'")){p.setString(1,s.name());p.setString(2,who);p.setString(3,note);p.setLong(4,id);return p.executeUpdate()==1;}} public boolean cancel(long id,String sid)throws SQLException{try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("UPDATE tblStudentChangeRequest SET status='CANCELLED' WHERE requestId=? AND studentId=? AND status='PENDING'")){p.setLong(1,id);p.setString(2,sid);return p.executeUpdate()==1;}}
 private static StudentChangeRequest map(ResultSet r)throws SQLException{StudentChangeRequest x=new StudentChangeRequest();x.setRequestId(r.getLong("requestId"));x.setStudentId(r.getString("studentId"));x.setStatus(StudentChangeStatus.valueOf(r.getString("status")));x.setSubmitTime(r.getTimestamp("submitTime"));x.setReviewerId(r.getString("reviewerId"));x.setReviewTime(r.getTimestamp("reviewTime"));x.setReviewRemark(r.getString("reviewRemark"));return x;}
}
