package dao;
import entity.StudentFamilyMember; import util.DBUtil; import java.sql.*; import java.util.*;
public class StudentFamilyMemberDAO {
 public List<StudentFamilyMember> findByStudentId(String id)throws SQLException{List<StudentFamilyMember>o=new ArrayList<>();try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM tblStudentFamilyMember WHERE studentId=? ORDER BY memberId")){p.setString(1,id);try(ResultSet r=p.executeQuery()){while(r.next()){StudentFamilyMember x=new StudentFamilyMember();x.setMemberId(r.getLong("memberId"));x.setStudentId(id);x.setName(r.getString("name"));x.setRelationship(r.getString("relationship"));x.setBirthDate(r.getDate("birthDate"));x.setRegisteredResidence(r.getString("registeredResidence"));x.setWorkplace(r.getString("workplace"));x.setWorkplaceAddress(r.getString("workplaceAddress"));x.setHealthStatus(r.getString("healthStatus"));x.setPhone(r.getString("phone"));o.add(x);}}}return o;}
 public StudentFamilyMember findById(String studentId,long id)throws SQLException{for(StudentFamilyMember x:findByStudentId(studentId))if(x.getMemberId()==id)return x;return null;}
 public boolean insert(StudentFamilyMember x)throws SQLException{try(Connection c=DBUtil.getConnection()){return insert(c,x);}}
 public boolean insert(Connection c,StudentFamilyMember x)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO tblStudentFamilyMember(studentId,name,relationship,birthDate,registeredResidence,workplace,workplaceAddress,healthStatus,phone)VALUES(?,?,?,?,?,?,?,?,?)")){p.setString(1,x.getStudentId());bind(p,x,2);return p.executeUpdate()==1;}}
 public boolean update(String studentId,StudentFamilyMember x)throws SQLException{try(Connection c=DBUtil.getConnection()){return update(c,studentId,x);}}
 public boolean update(Connection c,String studentId,StudentFamilyMember x)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE tblStudentFamilyMember SET name=?,relationship=?,birthDate=?,registeredResidence=?,workplace=?,workplaceAddress=?,healthStatus=?,phone=? WHERE memberId=? AND studentId=?")){bind(p,x,1);p.setLong(9,x.getMemberId());p.setString(10,studentId);return p.executeUpdate()==1;}}
 public boolean delete(String studentId,long id)throws SQLException{try(Connection c=DBUtil.getConnection()){return delete(c,studentId,id);}}
 public boolean delete(Connection c,String studentId,long id)throws SQLException{try(PreparedStatement p=c.prepareStatement("DELETE FROM tblStudentFamilyMember WHERE memberId=? AND studentId=?")){p.setLong(1,id);p.setString(2,studentId);return p.executeUpdate()==1;}}
 private void bind(PreparedStatement p,StudentFamilyMember x,int n)throws SQLException{p.setString(n++,x.getName());p.setString(n++,x.getRelationship());p.setDate(n++,x.getBirthDate());p.setString(n++,x.getRegisteredResidence());p.setString(n++,x.getWorkplace());p.setString(n++,x.getWorkplaceAddress());p.setString(n++,x.getHealthStatus());p.setString(n,x.getPhone());}
}
