package dao;
import entity.Teacher; import util.DBUtil; import java.lang.reflect.*; import java.sql.*; import java.util.*;
@SuppressWarnings({"SqlNoDataSourceInspection","SqlResolve"})
public class TeacherDAO {
 public static final List<String> COLUMNS=List.of("teacherId","UID","name","politicalStatus","nationality","gender","idType","idNumber","idIssueDate","birthDate","nativePlace","householdType","birthPlace","sourcePlace","registeredResidence","partyMember","partyJoinDate","healthStatus","employed","employmentStatus","campus","college","department","title","position","education","employmentStartDate","telephone","mobile","email","qq","wechat","officeAddress","emergencyContact","emergencyPhone");
 public Teacher findByUID(String v)throws SQLException{return one("SELECT * FROM tblTeacher WHERE UID=?",v);}
 public Teacher findByTeacherId(String v)throws SQLException{return one("SELECT * FROM tblTeacher WHERE teacherId=?",v);}
 private Teacher one(String sql,String v)throws SQLException{try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setString(1,v);try(ResultSet r=p.executeQuery()){return r.next()?map(r):null;}}}
 public List<Teacher> findAll()throws SQLException{List<Teacher> o=new ArrayList<>();try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM tblTeacher ORDER BY teacherId");ResultSet r=p.executeQuery()){while(r.next())o.add(map(r));}return o;}
 public boolean insert(Teacher t)throws SQLException{String cols=String.join(",",COLUMNS),qs=String.join(",",Collections.nCopies(COLUMNS.size(),"?"));try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO tblTeacher("+cols+")VALUES("+qs+")")){bind(p,t,COLUMNS);return p.executeUpdate()==1;}}
 public boolean update(Teacher t)throws SQLException{List<String> f=COLUMNS.subList(1,COLUMNS.size());String set=String.join(",",f.stream().map(x->x+"=?").toList());try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("UPDATE tblTeacher SET "+set+" WHERE teacherId=?")){bind(p,t,f);p.setString(f.size()+1,t.getTeacherId());return p.executeUpdate()==1;}}
 public boolean apply(Connection c,String id,List<entity.TeacherChangeItem> items)throws SQLException{Set<String> allowed=new HashSet<>(COLUMNS);allowed.remove("teacherId");allowed.remove("UID");String set=String.join(",",items.stream().map(i->{if(!allowed.contains(i.getFieldName()))throw new IllegalArgumentException("不可修改字段: "+i.getFieldName());return i.getFieldName()+"=?";}).toList());try(PreparedStatement p=c.prepareStatement("UPDATE tblTeacher SET "+set+" WHERE teacherId=?")){int n=1;for(var i:items)p.setObject(n++,convert(i.getFieldName(),i.getNewValue()));p.setString(n,id);return p.executeUpdate()==1;}}
 private static Object convert(String name,String value)throws SQLException{try{Class<?> t=Teacher.class.getDeclaredField(name).getType();String v=value==null?"":value.trim();if(t==boolean.class)return Set.of("true","1","是","在职").contains(v);if(t==java.sql.Date.class)return v.isBlank()?null:java.sql.Date.valueOf(v);return v;}catch(Exception e){throw new SQLException("字段格式错误: "+name,e);}}
 private static void bind(PreparedStatement p,Teacher t,List<String> fs)throws SQLException{try{int n=1;for(String x:fs){Field f=Teacher.class.getDeclaredField(x);f.setAccessible(true);p.setObject(n++,f.get(t));}}catch(Exception e){throw new SQLException(e);}}
 private static Teacher map(ResultSet r)throws SQLException{Teacher t=new Teacher();try{for(String x:COLUMNS){Field f=Teacher.class.getDeclaredField(x);f.setAccessible(true);if(f.getType()==boolean.class)f.setBoolean(t,r.getBoolean(x));else if(f.getType()==java.sql.Date.class)f.set(t,r.getDate(x));else f.set(t,r.getString(x));}return t;}catch(Exception e){throw new SQLException(e);}}
}
