package dao;
import entity.TeacherFamilyMember; import util.DBUtil; import java.sql.*; import java.util.*;
@SuppressWarnings({"SqlNoDataSourceInspection", "SqlResolve"})
public class TeacherFamilyMemberDAO {
 public List<TeacherFamilyMember> findByTeacherId(String id)throws SQLException{List<TeacherFamilyMember>o=new ArrayList<>();try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM tblTeacherFamilyMember WHERE teacherId=? ORDER BY memberId")){p.setString(1,id);try(ResultSet r=p.executeQuery()){while(r.next()){TeacherFamilyMember x=new TeacherFamilyMember();x.setMemberId(r.getLong("memberId"));x.setTeacherId(id);x.setName(r.getString("name"));x.setRelationship(r.getString("relationship"));x.setBirthDate(r.getDate("birthDate"));x.setRegisteredResidence(r.getString("registeredResidence"));x.setWorkplace(r.getString("workplace"));x.setWorkplaceAddress(r.getString("workplaceAddress"));x.setHealthStatus(r.getString("healthStatus"));x.setPhone(r.getString("phone"));o.add(x);}}}return o;}
 public TeacherFamilyMember findById(String teacherId,long id)throws SQLException{for(TeacherFamilyMember x:findByTeacherId(teacherId))if(x.getMemberId()==id)return x;return null;}
 public boolean insert(TeacherFamilyMember x)throws SQLException{try(Connection c=DBUtil.getConnection()){return insert(c,x);}}
 public boolean insert(Connection c,TeacherFamilyMember x)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO tblTeacherFamilyMember(teacherId,name,relationship,birthDate,registeredResidence,workplace,workplaceAddress,healthStatus,phone)VALUES(?,?,?,?,?,?,?,?,?)")){p.setString(1,x.getTeacherId());bind(p,x,2);return p.executeUpdate()==1;}}
 public boolean update(String teacherId,TeacherFamilyMember x)throws SQLException{try(Connection c=DBUtil.getConnection()){return update(c,teacherId,x);}}
 public boolean update(Connection c,String teacherId,TeacherFamilyMember x)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE tblTeacherFamilyMember SET name=?,relationship=?,birthDate=?,registeredResidence=?,workplace=?,workplaceAddress=?,healthStatus=?,phone=? WHERE memberId=? AND teacherId=?")){bind(p,x,1);p.setLong(9,x.getMemberId());p.setString(10,teacherId);return p.executeUpdate()==1;}}
 public boolean delete(String teacherId,long id)throws SQLException{try(Connection c=DBUtil.getConnection()){return delete(c,teacherId,id);}}
 public boolean delete(Connection c,String teacherId,long id)throws SQLException{try(PreparedStatement p=c.prepareStatement("DELETE FROM tblTeacherFamilyMember WHERE memberId=? AND teacherId=?")){p.setLong(1,id);p.setString(2,teacherId);return p.executeUpdate()==1;}}
 private void bind(PreparedStatement p,TeacherFamilyMember x,int n)throws SQLException{p.setString(n++,x.getName());p.setString(n++,x.getRelationship());p.setDate(n++,x.getBirthDate());p.setString(n++,x.getRegisteredResidence());p.setString(n++,x.getWorkplace());p.setString(n++,x.getWorkplaceAddress());p.setString(n++,x.getHealthStatus());p.setString(n,x.getPhone());}
}
