package dao;
import entity.TeacherWorkExperience;import util.DBUtil;import java.sql.*;import java.util.*;
public class TeacherWorkExperienceDAO {
 public List<TeacherWorkExperience> findByTeacherId(String id)throws SQLException{List<TeacherWorkExperience> result=new ArrayList<>();try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM tblTeacherWorkExperience WHERE teacherId=? ORDER BY startDate DESC")){p.setString(1,id);try(ResultSet r=p.executeQuery()){while(r.next()){TeacherWorkExperience x=new TeacherWorkExperience();x.setExperienceId(r.getLong("experienceId"));x.setTeacherId(id);x.setStartDate(r.getDate("startDate"));x.setEndDate(r.getDate("endDate"));x.setOrganization(r.getString("organization"));x.setDepartment(r.getString("department"));x.setPosition(r.getString("position"));x.setDescription(r.getString("description"));result.add(x);}}}return result;}
 public boolean insert(TeacherWorkExperience x)throws SQLException{try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO tblTeacherWorkExperience(teacherId,startDate,endDate,organization,department,position,description) VALUES(?,?,?,?,?,?,?)")){bind(p,x);return p.executeUpdate()==1;}}
 public boolean update(String teacherId,TeacherWorkExperience x)throws SQLException{try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("UPDATE tblTeacherWorkExperience SET startDate=?,endDate=?,organization=?,department=?,position=?,description=? WHERE experienceId=? AND teacherId=?")){p.setDate(1,x.getStartDate());p.setDate(2,x.getEndDate());p.setString(3,x.getOrganization());p.setString(4,x.getDepartment());p.setString(5,x.getPosition());p.setString(6,x.getDescription());p.setLong(7,x.getExperienceId());p.setString(8,teacherId);return p.executeUpdate()==1;}}
 public boolean delete(String teacherId,long id)throws SQLException{try(Connection c=DBUtil.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM tblTeacherWorkExperience WHERE experienceId=? AND teacherId=?")){p.setLong(1,id);p.setString(2,teacherId);return p.executeUpdate()==1;}}
 private void bind(PreparedStatement p,TeacherWorkExperience x)throws SQLException{p.setString(1,x.getTeacherId());p.setDate(2,x.getStartDate());p.setDate(3,x.getEndDate());p.setString(4,x.getOrganization());p.setString(5,x.getDepartment());p.setString(6,x.getPosition());p.setString(7,x.getDescription());}
}
