package service;
import dao.*; import entity.*; import enums.StudentChangeStatus; import util.DBUtil; import vo.TeacherOverviewVO; import java.sql.*; import java.util.*;
public class TeacherService {
 private static final Set<String> EDITABLE=Set.of("politicalStatus","nationality","gender","idType","idNumber","idIssueDate","birthDate","nativePlace","householdType","birthPlace","sourcePlace","registeredResidence","partyMember","partyJoinDate","healthStatus","campus","telephone","mobile","email","qq","wechat","officeAddress","emergencyContact","emergencyPhone");
 private final TeacherDAO teachers=new TeacherDAO(); private final TeacherChangeRequestDAO requests=new TeacherChangeRequestDAO();private final TeacherWorkExperienceDAO workExperiences=new TeacherWorkExperienceDAO();
 public TeacherOverviewVO queryByUID(String UID)throws SQLException{return overview(teachers.findByUID(UID));}
 public TeacherOverviewVO queryByTeacherId(String id)throws SQLException{return overview(teachers.findByTeacherId(id));}
 private TeacherOverviewVO overview(Teacher t)throws SQLException{if(t==null)return null;TeacherOverviewVO v=new TeacherOverviewVO();v.setTeacher(t);v.setPendingRequest(requests.findPendingByTeacherId(t.getTeacherId()));v.setLatestRequest(requests.findLatestByTeacherId(t.getTeacherId()));v.setWorkExperiences(workExperiences.findByTeacherId(t.getTeacherId()));return v;}
 public List<Teacher> listTeachers()throws SQLException{return teachers.findAll();} public List<TeacherChangeRequest> listAll()throws SQLException{return requests.findAll();}
 public TeacherChangeRequest queryRequest(long id)throws SQLException{TeacherChangeRequest r=requests.findById(id);if(r==null)throw new IllegalArgumentException("申请不存在");return r;}
 public long submit(String UID,TeacherChangeRequest r)throws SQLException{Teacher t=teachers.findByUID(UID);if(t==null)throw new IllegalArgumentException("当前用户没有教师档案");if(r==null||r.getItems()==null||r.getItems().isEmpty())throw new IllegalArgumentException("修改项不能为空");if(requests.findPendingByTeacherId(t.getTeacherId())!=null)throw new IllegalStateException("已有待审核申请");Set<String> seen=new HashSet<>();for(TeacherChangeItem i:r.getItems())if(!EDITABLE.contains(i.getFieldName())||!seen.add(i.getFieldName()))throw new SecurityException("无权修改字段: "+i.getFieldName());r.setTeacherId(t.getTeacherId());try(Connection c=DBUtil.getConnection()){c.setAutoCommit(false);try{long id=requests.insert(c,r);c.commit();return id;}catch(Exception e){c.rollback();throw e;}}}
 public void review(long id,StudentChangeStatus result,String reviewer,String note)throws SQLException{if(result!=StudentChangeStatus.APPROVED&&result!=StudentChangeStatus.REJECTED)throw new IllegalArgumentException("审核结果无效");try(Connection c=DBUtil.getConnection()){c.setAutoCommit(false);try{TeacherChangeRequest r=requests.findByIdForUpdate(c,id);if(r==null||r.getStatus()!=StudentChangeStatus.PENDING)throw new IllegalStateException("申请不存在或已处理");if(result==StudentChangeStatus.APPROVED&&!teachers.apply(c,r.getTeacherId(),r.getItems()))throw new SQLException("教师信息更新失败");if(!requests.review(c,id,result,reviewer,note))throw new IllegalStateException("申请状态已变化");if(result==StudentChangeStatus.APPROVED){Teacher t=teachers.findByTeacherId(r.getTeacherId());if(t!=null&&t.getUID()!=null)new dao.UserDAO().syncUserInfo(c,t.getUID());}c.commit();}catch(Exception e){c.rollback();throw e;}}}
 public boolean updateByAdmin(Teacher t)throws SQLException{if(t==null||t.getTeacherId()==null)throw new IllegalArgumentException("教师信息不能为空");boolean ok=teachers.update(t);if(ok&&t.getUID()!=null)new dao.UserDAO().syncUserInfo(t.getUID());return ok;}
 public boolean addWorkExperience(String UID,TeacherWorkExperience value)throws SQLException{Teacher teacher=requireTeacher(UID);validateExperience(value);value.setExperienceId(null);value.setTeacherId(teacher.getTeacherId());return requireChanged(workExperiences.insert(value),"工作经历添加失败");}
 public boolean updateWorkExperience(String UID,TeacherWorkExperience value)throws SQLException{Teacher teacher=requireTeacher(UID);validateExperience(value);if(value.getExperienceId()==null||value.getExperienceId()<=0)throw new IllegalArgumentException("工作经历编号无效");return requireChanged(workExperiences.update(teacher.getTeacherId(),value),"工作经历不存在或更新失败");}
 public boolean deleteWorkExperience(String UID,long id)throws SQLException{return requireChanged(workExperiences.delete(requireTeacher(UID).getTeacherId(),id),"工作经历不存在或删除失败");}
 private Teacher requireTeacher(String UID)throws SQLException{Teacher teacher=teachers.findByUID(UID);if(teacher==null)throw new IllegalArgumentException("当前用户没有教师档案");return teacher;}
 private void validateExperience(TeacherWorkExperience value){if(value==null)throw new IllegalArgumentException("工作经历不能为空");if(value.getStartDate()==null)throw new IllegalArgumentException("开始时间不能为空");if(value.getOrganization()==null||value.getOrganization().isBlank())throw new IllegalArgumentException("工作单位不能为空");if(value.getPosition()==null||value.getPosition().isBlank())throw new IllegalArgumentException("职务不能为空");if(value.getEndDate()!=null&&value.getEndDate().before(value.getStartDate()))throw new IllegalArgumentException("结束时间不能早于开始时间");}
 private boolean requireChanged(boolean changed,String message){if(!changed)throw new IllegalStateException(message);return true;}
}
