# \u6570\u636E\u5E93\u914D\u7F6E\u6587\u4EF6
# \u4FEE\u6539\u6210\u4F60\u81EA\u5DF1\u7684 MySQL \u914D\u7F6E

db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/virtual_campus?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
db.username=root
db.password=20260824